<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>AgentPrism.Ui.E2ETests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Playwright" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/AgentPrism.UI/AgentPrism.UI.csproj" />
    <ProjectReference Include="../../src/AgentPrism.Workflows/AgentPrism.Workflows.csproj" />
  </ItemGroup>

</Project>
