-- ---------------------------------------------------------------------------
-- 0031 — Audit trail hash chain (phase 64)
--
-- Adds `prev_hash`/`hash` to `audit_log`. Both columns are nullable: every row
-- written BEFORE this migration has neither (the column did not exist yet) and
-- is NOT backfilled — there is no portable way to compute a SHA-256 canonical
-- form in SQL across three dialects, and inventing one at migration time would
-- not match AuditChainHasher exactly. A pre-existing installation's chain
-- therefore starts at the first entry written AFTER the upgrade; older entries
-- are excluded from verification (SqlAuditLog.SelectAuditChain filters
-- `hash IS NOT NULL`) rather than misreported as tampered.
--
-- The unique index enforces "at most one writer wins a given (tenant, prev_hash)
-- pair" so a concurrent write race cannot fork the chain (SqlAuditLog retries
-- on the resulting uniqueness violation, the same pattern as SqlIdempotencyStore).
-- It is FILTERED to `hash IS NOT NULL` for the same backward-compatibility
-- reason above: an installation with existing rows has many NULL prev_hash
-- values already (one per pre-existing row) and an unfiltered index would fail
-- to apply at migration time.
--
-- 🚨 `before`/`after` change from `jsonb` to `json`. Measured: `jsonb` does NOT
-- round-trip the original text byte for byte (it reorders object keys and
-- changes whitespace) — the same K-027 reason `sessions.state` and
-- `conversation_items.item` are plain `json`. The hash chain needs the EXACT
-- text that was hashed at write time back at verify time; with `jsonb`, every
-- entry that carried a `before`/`after` value misreported as
-- AuditChainStatus.Broken after a normal read-back. `USING ... ::json` is a
-- direct, lossless cast (jsonb parses into the same value json stores as text).
--
-- 🚨 `chain_seq` exists ONLY to find "the tenant's most recently written row"
-- (SqlAuditLog.SelectLastAuditHash/SelectAuditChain order by it, DESC/ASC).
-- Measured: ordering by `(created_at, id)` — the obvious choice — is WRONG.
-- `id` is a uuid v7 (K-015); two entries written within the same TRUNCATED
-- microsecond (routine under concurrent writers, and now MORE likely because
-- this migration also rounds `created_at` to microseconds) tie-break on `id`,
-- whose low bits are RANDOM, not insertion order. A writer whose random id
-- happens to sort highest could be reported as "last" FOREVER, even after
-- later rows with numerically smaller ids are inserted — every writer racing
-- to extend the chain would then repeatedly read the SAME already-claimed
-- prev_hash and NEVER converge no matter how many times SqlAuditLog retries.
-- `GENERATED BY DEFAULT AS IDENTITY` is a real, monotonically increasing
-- sequence assigned by the database itself at insert time and is immune to
-- this — with single-statement autocommit inserts (the only kind this store
-- issues) sequence allocation order matches commit order exactly.
-- ---------------------------------------------------------------------------

ALTER TABLE {schema}.audit_log
    ADD COLUMN IF NOT EXISTS prev_hash text,
    ADD COLUMN IF NOT EXISTS hash      text;

ALTER TABLE {schema}.audit_log ALTER COLUMN before TYPE json USING before::json;
ALTER TABLE {schema}.audit_log ALTER COLUMN after  TYPE json USING after::json;

ALTER TABLE {schema}.audit_log
    ADD COLUMN IF NOT EXISTS chain_seq bigint GENERATED BY DEFAULT AS IDENTITY;

CREATE UNIQUE INDEX IF NOT EXISTS audit_log_tenant_prev_hash_idx
    ON {schema}.audit_log (tenant_id, COALESCE(prev_hash, ''))
    WHERE hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS audit_log_tenant_chain_seq_idx
    ON {schema}.audit_log (tenant_id, chain_seq DESC);
