namespace AgentPrism;

/// <summary>The result status of an OAuth authorization request.</summary>
public enum McpOAuthOperationStatus
{
    /// <summary>The request succeeded.</summary>
    Ok = 0,

    /// <summary>No server is registered with this name.</summary>
    ServerNotFound = 1,

    /// <summary>
    /// The server is not set up for OAuth, the flow is not
    /// <see cref="McpOAuthAuthorizationMode.AuthorizationCode"/>, or
    /// <c>AgentPrism:Mcp:OAuthCallbackBaseUri</c> is not configured.
    /// </summary>
    NotConfigured = 2,

    /// <summary>Could not connect to the server to get the authorization address (including timeout).</summary>
    ConnectionFailed = 3,

    /// <summary>The <c>state</c> is unknown or has expired (CSRF protection).</summary>
    InvalidState = 4,

    /// <summary>The provider rejected the code exchange, or the user cancelled authorization.</summary>
    AuthorizationFailed = 5,
}

/// <summary>The result of an OAuth start request.</summary>
public sealed record McpOAuthStartResult
{
    /// <summary>The result status.</summary>
    public required McpOAuthOperationStatus Status { get; init; }

    /// <summary>The authorization address the administrator is redirected to. Populated only for <see cref="McpOAuthOperationStatus.Ok"/>.</summary>
    public Uri? AuthorizationUri { get; init; }

    /// <summary>The single-use state value generated for CSRF protection.</summary>
    public string? State { get; init; }
}

/// <summary>The result of the OAuth callback.</summary>
public sealed record McpOAuthCompleteResult
{
    /// <summary>The result status.</summary>
    public required McpOAuthOperationStatus Status { get; init; }

    /// <summary>The name of the authorized server. <see langword="null"/> for <see cref="McpOAuthOperationStatus.InvalidState"/>.</summary>
    public string? ServerName { get; init; }

    /// <summary>The failure reason (safe to show to the user, carries no secret).</summary>
    public string? Error { get; init; }
}

/// <summary>
/// The coordinator that manages the OAuth Mode 1 (authorization code) flow for MCP servers.
/// </summary>
/// <remarks>
/// <para>
/// The abstraction lives in <c>AgentPrism.Abstractions</c> because
/// <c>AgentPrism.AspNetCore</c> (the endpoints) does not depend on the
/// <c>AgentPrism.Mcp</c> package — the same rationale as <see cref="IMcpToolRefresher"/>.
/// </para>
/// <para>
/// <strong>Tokens are never written to the database.</strong> At the end of a
/// successful flow, the access and refresh tokens are kept only in memory,
/// bounded by the process lifetime (docs/22-MCP-DERINLESMESI.md, section 22.3).
/// </para>
/// </remarks>
public interface IMcpOAuthCoordinator
{
    /// <summary>
    /// Starts the authorization flow for a server and returns the provider's
    /// authorization address.
    /// </summary>
    /// <param name="tenantId">The tenant identifier.</param>
    /// <param name="serverName">The server name.</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    ValueTask<McpOAuthStartResult> StartAsync(
        string tenantId,
        string serverName,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Handles the provider's callback request: forwards the code to the
    /// pending flow matched by <c>state</c> and waits for the token exchange result.
    /// </summary>
    /// <param name="state">The value generated by <see cref="McpOAuthStartResult.State"/>.</param>
    /// <param name="code">The authorization code returned by the provider.</param>
    /// <param name="iss">The RFC 9207 <c>iss</c> parameter (if present).</param>
    /// <param name="cancellationToken">The cancellation token.</param>
    ValueTask<McpOAuthCompleteResult> CompleteAsync(
        string state,
        string? code,
        string? iss,
        CancellationToken cancellationToken = default);
}
