namespace AgentPrism;

/// <summary>A draft for creating an API key.</summary>
/// <remarks>
/// The raw value, digest, and prefix are generated by
/// <see cref="IApiKeyStore.CreateAsync"/>; the draft carries only the
/// information given by the operator.
/// </remarks>
public sealed record ApiKeyDraft
{
    /// <summary>The tenant the key is bound to.</summary>
    public required string TenantId { get; init; }

    /// <summary>The name for the operator to recognize the key by.</summary>
    public required string Name { get; init; }

    /// <summary>The scope set. Must not be empty.</summary>
    public required IReadOnlyList<ApiKeyScope> Scopes { get; init; }

    /// <summary>The expiration. Never expires if <see langword="null"/>.</summary>
    public DateTimeOffset? ExpiresAt { get; init; }
}
