<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="../../src/Tracon.Core/Tracon.Core.csproj" />
    <ProjectReference Include="../../src/Tracon.Sqlite/Tracon.Sqlite.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
  </ItemGroup>

</Project>
