using System.Reflection;
using System.Text.Json;
using AgentPrism.Client.Generated;

namespace AgentPrism.Client.UnitTests;

/// <summary>
/// Proves that <see cref="AgentPrismApiClient"/> has a public method for every
/// <c>operationId</c> in <c>docs/openapi/agentprism.json</c> (section 83.2).
/// </summary>
/// <remarks>
/// The document is the production source; the generated client is a
/// downstream artifact regenerated by <c>dotnet nswag run nswag.json</c>. If
/// a phase adds an endpoint and regenerates the OpenAPI snapshot
/// (<c>OpenApiSnapshotTests</c>) without also re-running NSwag, this test
/// fails instead of the client silently going stale. There is no exemption
/// list: the document has zero operations without an <c>operationId</c>
/// today (measured 2026-08-21).
/// </remarks>
public sealed class ClientCoverageTests
{
    private static readonly string[] HttpMethods = ["get", "post", "put", "delete", "patch", "options", "head", "trace"];

    [Fact]
    public void Every_operationId_has_a_matching_client_method()
    {
        var operationIds = ReadOperationIds();

        var clientMethodNames = typeof(AgentPrismApiClient)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Select(method => method.Name)
            .ToHashSet(StringComparer.Ordinal);

        var missing = operationIds
            .Where(operationId => !clientMethodNames.Contains($"{operationId}Async"))
            .Order(StringComparer.Ordinal)
            .ToList();

        missing.ShouldBeEmpty(
            customMessage: $"{missing.Count} operationId(s) have no matching '<operationId>Async' method on " +
                            "AgentPrismApiClient. Regenerate the client: dotnet tool restore && " +
                            "python3 scripts/nswag-prepare-document.py docs/openapi/agentprism.json " +
                            "artifacts/openapi/agentprism.client-input.json && dotnet nswag run nswag.json && " +
                            "python3 scripts/nswag-postprocess-client.py src/AgentPrism.Client/Generated/AgentPrismApiClient.g.cs && " +
                            "python3 scripts/generate-client-json-context.py src/AgentPrism.Client/Generated/AgentPrismApiClient.g.cs " +
                            "src/AgentPrism.Client/Generated/AgentPrismClientJsonContext.g.cs");
    }

    [Fact]
    public void The_document_has_no_operation_without_an_operationId()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(DocumentPath));

        var operationsWithoutId = document.RootElement.GetProperty("paths").EnumerateObject()
            .SelectMany(path => path.Value.EnumerateObject())
            .Where(method => HttpMethods.Contains(method.Name, StringComparer.Ordinal))
            .Where(method => !method.Value.TryGetProperty("operationId", out _))
            .Count();

        // 83.2's coverage gate has no exemption list; this documents WHY -
        // if this ever fails, ClientCoverageTests above needs one.
        operationsWithoutId.ShouldBe(0);
    }

    private static List<string> ReadOperationIds()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(DocumentPath));

        return document.RootElement.GetProperty("paths").EnumerateObject()
            .SelectMany(path => path.Value.EnumerateObject())
            .Where(method => HttpMethods.Contains(method.Name, StringComparer.Ordinal))
            .Select(method => method.Value.GetProperty("operationId").GetString()!)
            .ToList();
    }

    private static string RepositoryRoot { get; } = FindRepositoryRoot();

    private static string DocumentPath { get; } =
        Path.Combine(RepositoryRoot, "docs", "openapi", "agentprism.json");

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "AgentPrism.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("AgentPrism.slnx not found.");
    }
}
