namespace AgentPrism.Generators.UnitTests;

/// <summary>
/// 52.5'in uc somut onlemini dogrular: <c>&lt;auto-generated/&gt;</c> basligi,
/// <c>dotnet format</c> ile uyumlu bicim ve AOT-guvenli (yansimasiz) kod.
/// </summary>
public sealed class GeneratedCodeStructureTests
{
    private const string Source = """
        using AgentPrism;

        namespace MyApp;

        internal static class Tools
        {
            [AgentPrismTool("get_order_status", "Bir siparisin durumunu dondurur.")]
            public static string GetOrderStatus(string orderId) => orderId;
        }
        """;

    [Fact]
    public void Her_uretilen_dosya_auto_generated_basligi_tasir()
    {
        var result = GeneratorTestHelper.Run(Source);

        result.GeneratedFiles().ShouldNotBeEmpty();

        foreach (var (hintName, text) in result.GeneratedFiles())
        {
            text.ShouldStartWith("// <auto-generated/>", customMessage: $"{hintName} basliksiz");
        }
    }

    [Fact]
    public void Uretilen_kod_sekme_veya_satir_sonu_bosluk_tasimaz()
    {
        // dotnet format'in en sik yakaladigi iki sorun: TAB karakteri ve satir
        // sonunda bosluk (IDE0055). Tam bir `dotnet format --verify-no-changes`
        // kosumu ornek uygulama uzerinde ayri bir dogrulama komutuyla yapilir
        // (docs/52-KAYNAK-URETECI.md); burada ureteç ciktisini izole ediyoruz.
        var result = GeneratorTestHelper.Run(Source);

        foreach (var (hintName, text) in result.GeneratedFiles())
        {
            text.ShouldNotContain('\t', customMessage: $"{hintName} TAB iceriyor");

            foreach (var line in text.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                trimmed.ShouldBe(trimmed.TrimEnd(' '), customMessage: $"{hintName} satir sonunda bosluk iceriyor: '{trimmed}'");
            }
        }
    }

    [Fact]
    public void Uretilen_kod_yansima_API_lerini_kullanmaz()
    {
        // AOT DoD'si: uretilen yol [RequiresUnreferencedCode]/[RequiresDynamicCode]
        // GEREKTIRMEMELIDIR. Bunun yapisal kaniti, kodun yansima API'lerine hic
        // basvurmamasidir - gercek AOT yayinlama denetimi (IL2026/IL3050 taramasi)
        // ornek uygulama uzerinde ayri bir dogrulama komutuyla yapilir.
        var result = GeneratorTestHelper.Run(Source);

        string[] forbidden = ["System.Reflection", "Activator.", "GetMethod(", "GetMethods(", "MakeGenericType", "InvokeMember"];

        foreach (var (hintName, text) in result.GeneratedFiles())
        {
            foreach (var pattern in forbidden)
            {
                text.ShouldNotContain(pattern, customMessage: $"{hintName} yansima izi tasiyor: {pattern}");
            }
        }
    }

    [Fact]
    public void Uretilen_sinif_dogrudan_AIFunction_turetir_ve_AIFunctionFactory_kullanmaz()
    {
        // Delege tabanli AIFunctionFactory.Create de yansima tasir (RequiresUnreferencedCode);
        // uretecin AOT vaadi ancak DOGRUDAN AIFunction turetmekle saglanir.
        var result = GeneratorTestHelper.Run(Source);

        var wrapper = result.SingleWrapperFile();

        wrapper.ShouldContain(": global::Microsoft.Extensions.AI.AIFunction");
        wrapper.ShouldNotContain("AIFunctionFactory");
    }
}
