using System.Text;

namespace Tracon.Generators;

/// <summary>
/// Emits formatted (dotnet format compatible) C# source, carrying an <auto-generated/>
/// header, from a <see cref="ToolEmitModel"/>.
/// </summary>
internal static class SourceWriter
{
    private const string Header = "// <auto-generated/>\n#nullable enable\n\n";

    /// <summary>Emits an <c>AIFunction</c>-derived wrapper class for one tool.</summary>
    public static string WriteToolWrapper(ToolEmitModel model)
    {
        var sb = new StringBuilder(Header);

        sb.Append("namespace Tracon.Generated;\n\n");
        sb.Append("/// <summary>Generated tool wrapper: ")
          .Append(model.ContainingTypeDisplay).Append('.').Append(model.MethodName)
          .Append(".</summary>\n");
        sb.Append("internal sealed class ").Append(model.GeneratedClassName).Append(" : global::Microsoft.Extensions.AI.AIFunction\n{\n");

        sb.Append("    private static readonly global::System.Text.Json.JsonDocument SchemaDocument =\n")
          .Append("        global::System.Text.Json.JsonDocument.Parse(")
          .Append(ToStringLiteral(BuildSchema(model.Parameters)))
          .Append(");\n\n");

        sb.Append("    public override string Name => ").Append(ToStringLiteral(model.ToolName)).Append(";\n\n");
        // AITool.Description's NRT signature is a NON-nullable string (verified: CS8764,
        // Microsoft.Extensions.AI.Abstractions 10.9.0). When there is no description (APG0006
        // already warns), an empty string is returned - NOT null.
        sb.Append("    public override string Description => ")
          .Append(ToStringLiteral(model.Description ?? string.Empty))
          .Append(";\n\n");
        sb.Append("    public override global::System.Text.Json.JsonElement JsonSchema => SchemaDocument.RootElement;\n\n");

        sb.Append("    protected override ");
        sb.Append(RequiresAwait(model.Return) ? "async " : string.Empty);
        sb.Append("global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(\n")
          .Append("        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,\n")
          .Append("        global::System.Threading.CancellationToken cancellationToken)\n    {\n");

        var callArguments = new List<string>();

        foreach (var parameter in model.Parameters)
        {
            if (parameter.Shape == ParameterShape.CancellationToken)
            {
                callArguments.Add("cancellationToken");
                continue;
            }

            var variableName = "@" + parameter.Name;
            sb.Append("        var ").Append(variableName).Append(" = ").Append(WriteBinding(parameter, model.JsonSerializerContextTypeDisplay)).Append(";\n");
            callArguments.Add(variableName);
        }

        // ContainingTypeDisplay already starts with "global::..." (FullyQualifiedFormat).
        var invocation = $"{model.ContainingTypeDisplay}.{model.MethodName}({string.Join(", ", callArguments)})";

        switch (model.Return)
        {
            case ReturnKind.None:
                sb.Append("        ").Append(invocation).Append(";\n");
                sb.Append("        return new global::System.Threading.Tasks.ValueTask<object?>(result: null);\n");
                break;
            case ReturnKind.Value:
                sb.Append("        var result = ").Append(invocation).Append(";\n");
                sb.Append("        return new global::System.Threading.Tasks.ValueTask<object?>(")
                  .Append(WriteResult(model, "result")).Append(");\n");
                break;
            case ReturnKind.AsyncNone:
                sb.Append("        await ").Append(invocation).Append(".ConfigureAwait(false);\n");
                sb.Append("        return null;\n");
                break;
            case ReturnKind.AsyncValue:
                sb.Append("        var result = await ").Append(invocation).Append(".ConfigureAwait(false);\n");
                sb.Append("        return ").Append(WriteResult(model, "result")).Append(";\n");
                break;
        }

        sb.Append("    }\n}\n");

        return sb.ToString();
    }

    /// <summary>Emits the entry point that gathers all tool registrations and the <c>AddGeneratedTools()</c> extension.</summary>
    public static string WriteAggregator(IReadOnlyList<ToolEmitModel> tools)
    {
        var sb = new StringBuilder(Header);

        sb.Append("using global::Microsoft.Extensions.DependencyInjection;\n\n");

        // The file-scoped (`namespace X;`) form is limited to a SINGLE namespace per file
        // (CS8954); since two namespaces are needed, the BLOCK form is used instead.
        sb.Append("namespace Tracon.Generated\n{\n");
        sb.Append("    /// <summary>All tool registrations found by the source generator.</summary>\n");
        sb.Append("    internal static class TraconGeneratedTools\n    {\n");
        sb.Append("        /// <summary>Creates all generated tool registrations in this assembly.</summary>\n");
        sb.Append("        public static global::System.Collections.Generic.IReadOnlyList<global::Tracon.TraconToolRegistration> Create()\n");
        sb.Append("            => new global::Tracon.TraconToolRegistration[]\n            {\n");

        foreach (var model in tools)
        {
            sb.Append("                new(new ").Append(model.GeneratedClassName).Append("(), requiresApproval: ")
              .Append(model.RequiresApproval ? "true" : "false")
              .Append(", effect: (global::Tracon.ToolEffect)").Append(model.Effect)
              .Append(", requiredPermission: ").Append(model.RequiredPermission is null ? "null" : ToStringLiteral(model.RequiredPermission))
              .Append(", timeout: ").Append(model.TimeoutSeconds > 0
                  ? $"global::System.TimeSpan.FromSeconds({model.TimeoutSeconds})"
                  : "null")
              .Append(", safeToRepeat: ").Append(model.SafeToRepeat ? "true" : "false")
              .Append(", maxOutputBytes: ").Append(model.MaxOutputBytes > 0 ? model.MaxOutputBytes.ToString(System.Globalization.CultureInfo.InvariantCulture) : "null")
              .Append("),\n");
        }

        sb.Append("            };\n    }\n}\n\n");

        sb.Append("namespace Tracon\n{\n");
        sb.Append("    /// <summary>Adds the tool registrations found by the source generator to <see cref=\"ITraconBuilder\"/>.</summary>\n");
        sb.Append("    public static class TraconGeneratedToolsBuilderExtensions\n    {\n");
        sb.Append("        /// <summary>\n");
        sb.Append("        /// Registers every method marked with <c>[TraconTool]</c> in this assembly, WITHOUT\n");
        sb.Append("        /// using reflection. Use <c>AddToolsFrom</c> for tools in another assembly.\n");
        sb.Append("        /// </summary>\n");
        sb.Append("        /// <param name=\"builder\">The Tracon configuration chain.</param>\n");
        sb.Append("        /// <returns>The chain, for continuation.</returns>\n");
        sb.Append("        public static global::Tracon.ITraconBuilder AddGeneratedTools(this global::Tracon.ITraconBuilder builder)\n        {\n");
        sb.Append("            global::System.ArgumentNullException.ThrowIfNull(builder);\n\n");
        sb.Append("            foreach (var registration in global::Tracon.Generated.TraconGeneratedTools.Create())\n            {\n");
        sb.Append("                builder.Services.AddSingleton(registration);\n");
        sb.Append("            }\n\n");
        sb.Append("            return builder;\n        }\n    }\n}\n");

        return sb.ToString();
    }

    private static bool RequiresAwait(ReturnKind kind) => kind is ReturnKind.AsyncNone or ReturnKind.AsyncValue;

    private static string WriteResult(ToolEmitModel model, string value)
        => model.SerializedResultTypeDisplay is { } resultType
            ? $"global::System.Text.Json.JsonSerializer.SerializeToElement({value}, {model.JsonSerializerContextTypeDisplay}.Default.GetTypeInfo(typeof({resultType}))!)"
            : $"(object?){value}";

    private static string WriteBinding(ParameterModel parameter, string? jsonSerializerContextTypeDisplay)
    {
        var nameLiteral = ToStringLiteral(parameter.Name);

        if (parameter.Shape is ParameterShape.Array or ParameterShape.ObjectArray)
        {
            var elementConverter = parameter.Shape == ParameterShape.Array
                ? WriteElementConverter(parameter.Leaf!)
                : WriteObjectConverter(parameter.Object!, jsonSerializerContextTypeDisplay!);
            var required = parameter.IsRequired ? "true" : "false";
            var defaultValue = parameter.IsRequired ? "null" : (parameter.DefaultValueLiteral ?? "null");

            var getArrayCall = $"global::Tracon.TraconGeneratedToolArguments.GetArray(arguments, {nameLiteral}, static e => {elementConverter}, required: {required}, defaultValue: {defaultValue})";

            // GetArray returns IReadOnlyList<T>. When the target parameter is a bare array
            // (T[]), there is no implicit conversion (CS1503); .ToArray() converts it explicitly.
            return parameter.IsConcreteArray
                ? $"global::System.Linq.Enumerable.ToArray({getArrayCall})"
                : getArrayCall;
        }

        var converter = parameter.Shape == ParameterShape.Object
            ? WriteObjectConverter(parameter.Object!, jsonSerializerContextTypeDisplay!)
            : WriteElementConverter(parameter.Leaf!);

        return parameter.IsRequired
            ? $"global::Tracon.TraconGeneratedToolArguments.GetRequired(arguments, {nameLiteral}, static e => {converter})"
            : $"global::Tracon.TraconGeneratedToolArguments.GetOptional(arguments, {nameLiteral}, static e => {converter}, {parameter.DefaultValueLiteral ?? "default"})";
    }

    /// <summary>
    /// Deserializes one object-shaped argument through the tool owner's own
    /// <c>JsonSerializerContext</c> - the generator never emits its own context, so
    /// binding always reaches for the one <c>TraconTool.JsonSerializerContext</c>
    /// names. <paramref name="jsonSerializerContextTypeDisplay"/> is never
    /// <see langword="null"/> here: APG0011 already blocks generation for any
    /// object-shaped parameter whose tool has no context declaring every type in its graph.
    /// </summary>
    private static string WriteObjectConverter(ObjectType objectType, string jsonSerializerContextTypeDisplay)
    {
        var inner = $"({objectType.ClrTypeDisplay})global::System.Text.Json.JsonSerializer.Deserialize(e, {jsonSerializerContextTypeDisplay}.Default.GetTypeInfo(typeof({objectType.ClrTypeDisplay}))!)!";

        return objectType.IsNullable
            ? $"e.ValueKind == global::System.Text.Json.JsonValueKind.Null ? ({objectType.ClrTypeDisplay}?)null : ({inner})"
            : inner;
    }

    private static string WriteElementConverter(LeafType leaf)
    {
        var inner = WriteNonNullConverter(leaf);

        if (!leaf.IsNullable)
        {
            return inner;
        }

        return $"e.ValueKind == global::System.Text.Json.JsonValueKind.Null ? ({leaf.ClrTypeDisplay}?)null : ({inner})";
    }

    private static string WriteNonNullConverter(LeafType leaf) => leaf.Kind switch
    {
        LeafTypeKind.Boolean => "e.GetBoolean()",
        LeafTypeKind.String => "e.GetString()!",
        LeafTypeKind.Guid => "e.GetGuid()",
        LeafTypeKind.DateTime => "e.GetDateTime()",
        LeafTypeKind.DateTimeOffset => "e.GetDateTimeOffset()",
        LeafTypeKind.Enum => $"global::System.Enum.Parse<{leaf.ClrTypeDisplay}>(e.GetString()!, ignoreCase: true)",
        LeafTypeKind.Integer or LeafTypeKind.Number => WriteNumericConverter(leaf.ClrTypeDisplay),
        _ => throw new InvalidOperationException($"Unexpected leaf type: {leaf.Kind}"),
    };

    private static string WriteNumericConverter(string clrTypeDisplay) => clrTypeDisplay switch
    {
        "global::System.SByte" => "e.GetSByte()",
        "global::System.Byte" => "e.GetByte()",
        "global::System.Int16" => "e.GetInt16()",
        "global::System.UInt16" => "e.GetUInt16()",
        "global::System.Int32" => "e.GetInt32()",
        "global::System.UInt32" => "e.GetUInt32()",
        "global::System.Int64" => "e.GetInt64()",
        "global::System.UInt64" => "e.GetUInt64()",
        "global::System.Single" => "e.GetSingle()",
        "global::System.Double" => "e.GetDouble()",
        "global::System.Decimal" => "e.GetDecimal()",
        _ => throw new InvalidOperationException($"Unexpected numeric type: {clrTypeDisplay}"),
    };

    private static string BuildSchema(EquatableArray<ParameterModel> parameters)
    {
        var properties = new StringBuilder();
        var required = new List<string>();
        var first = true;

        foreach (var parameter in parameters)
        {
            if (parameter.Shape == ParameterShape.CancellationToken)
            {
                continue;
            }

            if (!first)
            {
                properties.Append(',');
            }

            first = false;

            properties.Append('"').Append(JsonEscape(parameter.Name)).Append("\":").Append(BuildSchemaNode(parameter));

            if (parameter.IsRequired)
            {
                required.Add(parameter.Name);
            }
        }

        var requiredJson = string.Join(",", required.ConvertAll(name => $"\"{JsonEscape(name)}\""));

        return $"{{\"type\":\"object\",\"properties\":{{{properties}}},\"required\":[{requiredJson}],\"additionalProperties\":false}}";
    }

    private static string BuildSchemaNode(ParameterModel parameter)
    {
        string node;

        if (parameter.Shape is ParameterShape.Object or ParameterShape.ObjectArray)
        {
            var objectNode = BuildObjectSchema(parameter.Object!);
            node = parameter.Shape == ParameterShape.ObjectArray
                ? $"{{\"type\":\"array\",\"items\":{objectNode}}}"
                : objectNode;
        }
        else
        {
            var leafNode = BuildLeafSchemaNode(parameter.Leaf!, parameter.Constraints);

            // A length constraint on an array targets the array itself (minItems/maxItems),
            // never its element leaf - "at least two tags", not "each tag at least two
            // characters" (130.3). It is appended to the array node, after "items" closes,
            // never inside it.
            node = parameter.Shape == ParameterShape.Array
                ? AppendConstraintSuffix($"{{\"type\":\"array\",\"items\":{leafNode}}}", "minItems", parameter.Constraints?.MinItems, "maxItems", parameter.Constraints?.MaxItems)
                : leafNode;
        }

        // The description belongs on the PARAMETER node, not the array element leaf -
        // writing it into the leaf would nest it under "items", where the model does not
        // read it as the parameter's own description (125.1).
        return parameter.Description is { Length: > 0 } description
            ? $"{{\"description\":\"{JsonEscape(description)}\",{node.Substring(1)}"
            : node;
    }

    /// <summary>
    /// Builds a nested object's schema node - <c>{"type":"object","properties":{...},
    /// "required":[...],"additionalProperties":false}</c> - the SAME shape the root schema
    /// uses (135.2): one writer function for both, so the root and a nested object can never
    /// silently drift into two different contracts.
    /// </summary>
    private static string BuildObjectSchema(ObjectType objectType)
    {
        var properties = new StringBuilder();
        var required = new List<string>();
        var first = true;

        foreach (var member in objectType.Members)
        {
            if (!first)
            {
                properties.Append(',');
            }

            first = false;

            properties.Append('"').Append(JsonEscape(member.JsonName)).Append("\":").Append(BuildMemberSchemaNode(member));

            if (member.IsRequired)
            {
                required.Add(member.JsonName);
            }
        }

        var requiredJson = string.Join(",", required.ConvertAll(name => $"\"{JsonEscape(name)}\""));

        return $"{{\"type\":\"object\",\"properties\":{{{properties}}},\"required\":[{requiredJson}],\"additionalProperties\":false}}";
    }

    /// <summary>An object member's schema node - the same constraint and description handling applies here exactly as it does at the top level.</summary>
    private static string BuildMemberSchemaNode(ObjectMember member)
    {
        var node = member.Shape switch
        {
            ParameterShape.Scalar => BuildLeafSchemaNode(member.Leaf!, member.Constraints),
            ParameterShape.Array => AppendConstraintSuffix(
                $"{{\"type\":\"array\",\"items\":{BuildLeafSchemaNode(member.Leaf!, member.Constraints)}}}",
                "minItems", member.Constraints?.MinItems, "maxItems", member.Constraints?.MaxItems),
            ParameterShape.Object => BuildObjectSchema(member.Object!),
            ParameterShape.ObjectArray => $"{{\"type\":\"array\",\"items\":{BuildObjectSchema(member.Object!)}}}",
            _ => throw new InvalidOperationException($"Unexpected member shape: {member.Shape}"),
        };

        return member.Description is { Length: > 0 } description
            ? $"{{\"description\":\"{JsonEscape(description)}\",{node.Substring(1)}"
            : node;
    }

    /// <summary>
    /// Builds a leaf (or array element) schema node: its type keyword, then - in the
    /// fixed order <c>minimum</c>, <c>maximum</c>, <c>minLength</c>, <c>maxLength</c>,
    /// <c>pattern</c> (130.3) - whichever JSON Schema constraints <paramref name="constraints"/>
    /// carries. <c>minItems</c>/<c>maxItems</c> are not leaf constraints; see
    /// <see cref="BuildSchemaNode"/>.
    /// </summary>
    private static string BuildLeafSchemaNode(LeafType leaf, ParameterConstraints? constraints)
    {
        var typeNode = leaf.Kind switch
        {
            LeafTypeKind.Boolean => "{\"type\":\"boolean\"}",
            LeafTypeKind.Integer => "{\"type\":\"integer\"}",
            LeafTypeKind.Number => "{\"type\":\"number\"}",
            LeafTypeKind.String => "{\"type\":\"string\"}",
            LeafTypeKind.Guid => "{\"type\":\"string\",\"format\":\"uuid\"}",
            LeafTypeKind.DateTime or LeafTypeKind.DateTimeOffset => "{\"type\":\"string\",\"format\":\"date-time\"}",
            LeafTypeKind.Enum => "{\"type\":\"string\",\"enum\":[" + string.Join(",", leaf.EnumMemberNames.Select(n => $"\"{JsonEscape(n)}\"")) + "]}",
            _ => throw new InvalidOperationException($"Unexpected leaf type: {leaf.Kind}"),
        };

        if (constraints is null || constraints.IsEmpty)
        {
            return typeNode;
        }

        var sb = new StringBuilder(typeNode, 0, typeNode.Length - 1, typeNode.Length + 64);

        if (constraints.Minimum is { } minimum)
        {
            sb.Append(",\"minimum\":").Append(minimum);
        }

        if (constraints.Maximum is { } maximum)
        {
            sb.Append(",\"maximum\":").Append(maximum);
        }

        if (constraints.MinLength is { } minLength)
        {
            sb.Append(",\"minLength\":").Append(minLength.ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        if (constraints.MaxLength is { } maxLength)
        {
            sb.Append(",\"maxLength\":").Append(maxLength.ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        if (constraints.Pattern is { } pattern)
        {
            sb.Append(",\"pattern\":\"").Append(JsonEscape(pattern)).Append('"');
        }

        return sb.Append('}').ToString();
    }

    /// <summary>
    /// Appends up to two optional integer constraints (<c>minItems</c>/<c>maxItems</c>) to
    /// an already-complete JSON object literal, before its closing brace.
    /// </summary>
    private static string AppendConstraintSuffix(string node, string firstKey, int? firstValue, string secondKey, int? secondValue)
    {
        if (firstValue is null && secondValue is null)
        {
            return node;
        }

        var sb = new StringBuilder(node, 0, node.Length - 1, node.Length + 48);

        if (firstValue is { } first)
        {
            sb.Append(",\"").Append(firstKey).Append("\":").Append(first.ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        if (secondValue is { } second)
        {
            sb.Append(",\"").Append(secondKey).Append("\":").Append(second.ToString(System.Globalization.CultureInfo.InvariantCulture));
        }

        return sb.Append('}').ToString();
    }

    /// <summary>
    /// Escapes a value for embedding inside the JSON text this class builds by hand.
    /// Tool/parameter/enum names never carry control characters, but a free-text
    /// <c>[Description]</c> can (125.1) - an unescaped literal newline inside a JSON
    /// string is invalid per RFC 8259 and <c>JsonDocument.Parse</c> throws on it.
    /// </summary>
    private static string JsonEscape(string value)
    {
        var sb = new StringBuilder(value.Length);

        foreach (var c in value)
        {
            switch (c)
            {
                case '\\':
                    sb.Append("\\\\");
                    break;
                case '"':
                    sb.Append("\\\"");
                    break;
                case '\n':
                    sb.Append("\\n");
                    break;
                case '\r':
                    sb.Append("\\r");
                    break;
                case '\t':
                    sb.Append("\\t");
                    break;
                default:
                    if (c < ' ')
                    {
                        sb.Append("\\u").Append(((int)c).ToString("x4", System.Globalization.CultureInfo.InvariantCulture));
                    }
                    else
                    {
                        sb.Append(c);
                    }

                    break;
            }
        }

        return sb.ToString();
    }

    private static string ToStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2).Append('"');

        foreach (var c in value)
        {
            sb.Append(c switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\n' => "\\n",
                '\r' => "\\r",
                _ => c.ToString(),
            });
        }

        return sb.Append('"').ToString();
    }
}
