using Microsoft.Extensions.AI;

namespace AgentPrism;

/// <summary>
/// Accumulates token usage generated by context compaction (summarization) during a run.
/// </summary>
/// <remarks>
/// The summarization call is a side channel that is fully separate from the agent's
/// <c>AgentResponse</c>, so its tokens never enter the normal flow. This accumulator
/// is available through <see cref="AgentPrismRunContext"/>. At run completion,
/// <see cref="RunRecordingAgent"/> adds its value to final <see cref="RunUsage"/>,
/// so both cost reports and the graph budget include summarization cost.
/// </remarks>
internal sealed class CompactionUsageAccumulator
{
    private long _inputTokens;
    private long _outputTokens;
    private long _totalTokens;

    /// <summary>Adds usage from one summarization call to the accumulator.</summary>
    /// <param name="usage">The call usage details. Ignores <see langword="null"/>.</param>
    public void Add(UsageDetails? usage)
    {
        if (usage is null)
        {
            return;
        }

        if (usage.InputTokenCount is { } input)
        {
            Interlocked.Add(ref _inputTokens, input);
        }

        if (usage.OutputTokenCount is { } output)
        {
            Interlocked.Add(ref _outputTokens, output);
        }

        if (usage.TotalTokenCount is { } total)
        {
            Interlocked.Add(ref _totalTokens, total);
        }
    }

    /// <summary>Converts the accumulated usage to <see cref="RunUsage"/>.</summary>
    /// <returns><see langword="null"/> when no usage was accumulated.</returns>
    public RunUsage? ToRunUsage()
    {
        var input = Interlocked.Read(ref _inputTokens);
        var output = Interlocked.Read(ref _outputTokens);
        var total = Interlocked.Read(ref _totalTokens);

        if (input == 0 && output == 0 && total == 0)
        {
            return null;
        }

        return new RunUsage
        {
            InputTokens = input == 0 ? null : input,
            OutputTokens = output == 0 ? null : output,
            TotalTokens = total == 0 ? null : total,
        };
    }
}
