using System.Text.Json;
using Microsoft.Extensions.AI;

namespace AgentPrism;

/// <summary>
/// The helper methods called by tool wrappers produced by the source
/// generator (Phase 52) while converting JSON arguments to CLR types.
/// </summary>
/// <remarks>
/// <para>
/// This class is designed to be called only by code generated by the
/// <c>[AgentPrismTool]</c> generator; calling it by hand is not a supported
/// scenario. The only reason it is public is that the generated code lives
/// in the consumer's OWN assembly and therefore needs to reach this type from outside this compilation.
/// </para>
/// <para>
/// No conversion <strong>uses reflection</strong>: everything works through
/// <see cref="JsonElement"/>'s type-specific <c>Get*</c> methods or through
/// the converter delegate the caller supplies.
/// </para>
/// </remarks>
public static class AgentPrismGeneratedToolArguments
{
    /// <summary>Reads a required argument; throws if missing.</summary>
    /// <typeparam name="T">The target CLR type.</typeparam>
    /// <param name="arguments">The call's arguments.</param>
    /// <param name="name">The argument's JSON key.</param>
    /// <param name="convert">The converter that turns a <see cref="JsonElement"/> into <typeparamref name="T"/>.</param>
    /// <returns>The converted value.</returns>
    /// <exception cref="AgentPrismException">The argument is missing, or is an unexpected CLR type.</exception>
    public static T GetRequired<T>(AIFunctionArguments arguments, string name, Func<JsonElement, T> convert)
    {
        ArgumentNullException.ThrowIfNull(arguments);
        ArgumentNullException.ThrowIfNull(convert);

        if (!arguments.TryGetValue(name, out var raw) || raw is null)
        {
            throw new AgentPrismException($"The '{name}' argument is missing.");
        }

        return Convert(raw, convert, name);
    }

    /// <summary>Reads an optional argument; returns the given default if missing.</summary>
    /// <typeparam name="T">The target CLR type.</typeparam>
    /// <param name="arguments">The call's arguments.</param>
    /// <param name="name">The argument's JSON key.</param>
    /// <param name="convert">The converter that turns a <see cref="JsonElement"/> into <typeparamref name="T"/>.</param>
    /// <param name="defaultValue">The value to use if the argument is missing.</param>
    /// <returns>The converted value, or <paramref name="defaultValue"/>.</returns>
    /// <exception cref="AgentPrismException">The argument was given but is an unexpected CLR type.</exception>
    public static T GetOptional<T>(AIFunctionArguments arguments, string name, Func<JsonElement, T> convert, T defaultValue)
    {
        ArgumentNullException.ThrowIfNull(arguments);
        ArgumentNullException.ThrowIfNull(convert);

        if (!arguments.TryGetValue(name, out var raw) || raw is null)
        {
            return defaultValue;
        }

        return Convert(raw, convert, name);
    }

    /// <summary>Reads an array argument; each element is converted with the same converter.</summary>
    /// <typeparam name="T">The array element type.</typeparam>
    /// <param name="arguments">The call's arguments.</param>
    /// <param name="name">The argument's JSON key.</param>
    /// <param name="convert">The converter that converts each element.</param>
    /// <param name="required">Whether to throw if the argument is missing.</param>
    /// <param name="defaultValue">
    /// The value to use if <paramref name="required"/> is <see langword="false"/>
    /// and the argument is missing. An empty list is used if <see langword="null"/>.
    /// </param>
    /// <returns>The converted array.</returns>
    /// <exception cref="AgentPrismException">
    /// The argument is required but missing, or the given value is not a JSON array.
    /// </exception>
    public static IReadOnlyList<T> GetArray<T>(
        AIFunctionArguments arguments,
        string name,
        Func<JsonElement, T> convert,
        bool required,
        IReadOnlyList<T>? defaultValue)
    {
        ArgumentNullException.ThrowIfNull(arguments);
        ArgumentNullException.ThrowIfNull(convert);

        if (!arguments.TryGetValue(name, out var raw) || raw is null)
        {
            if (required)
            {
                throw new AgentPrismException($"The '{name}' argument is missing.");
            }

            return defaultValue ?? [];
        }

        if (raw is JsonElement { ValueKind: JsonValueKind.Array } element)
        {
            var list = new List<T>(element.GetArrayLength());

            foreach (var item in element.EnumerateArray())
            {
                list.Add(convert(item));
            }

            return list;
        }

        throw new AgentPrismException($"The '{name}' argument must be a JSON array; received type: {raw.GetType()}.");
    }

    private static T Convert<T>(object raw, Func<JsonElement, T> convert, string name)
    {
        if (raw is JsonElement element)
        {
            return convert(element);
        }

        if (raw is T typed)
        {
            return typed;
        }

        throw new AgentPrismException($"The '{name}' argument is an unexpected CLR type: {raw.GetType()}.");
    }
}
