using System.Text;
using System.Text.RegularExpressions;

namespace Tracon.Core.UnitTests.Architecture;

/// <summary>
/// Keeps the capability map in step with the code: every public registration
/// entry point must be named on the capability map page.
/// </summary>
/// <remarks>
/// <para>
/// The map is what a coding agent reads — <c>AGENTS.md</c>, <c>llms.txt</c>, and
/// the published page are all generated from
/// <c>docs-site/src/content/docs/capabilities.md</c>. Nothing else notices when
/// the code grows a new capability and the map does not follow, and a map that
/// is missing an entry point is worse than no map: the agent concludes the
/// capability does not exist and writes it by hand.
/// </para>
/// <para>
/// The entry point set is <see cref="CapabilityEntryPoints"/>, shared with
/// <see cref="CapabilityExampleTests"/> so the two gates cannot drift apart.
/// </para>
/// <para>
/// A ratchet, not a snapshot, in the shape of <see cref="SourceLanguageTests"/>.
/// <c>capability-coverage-baseline.txt</c> lists the entry points that are
/// allowed to be absent from the map. The list may only shrink: a new absence
/// fails, and so does a stale entry that is now covered.
/// </para>
/// <para>
/// Refresh after deliberately changing what is covered:
/// <c>TRACON_CAPABILITY_COVERAGE_REFRESH=1 dotnet test tests/Tracon.Core.UnitTests -c Release</c>.
/// </para>
/// </remarks>
public sealed class CapabilityCoverageTests
{
    private const string RefreshEnvVar = "TRACON_CAPABILITY_COVERAGE_REFRESH";

    [Fact]
    public void Every_registration_entry_point_is_named_on_the_capability_map()
    {
        var entryPoints = CapabilityEntryPoints.Names;

        entryPoints.ShouldNotBeEmpty("No entry point was read; the PublicAPI files or the parser changed shape.");

        var map = File.ReadAllText(CapabilityMapPath);
        var uncovered = entryPoints.Where(name => !IsNamed(map, name)).ToList();

        if (string.Equals(Environment.GetEnvironmentVariable(RefreshEnvVar), "1", StringComparison.Ordinal))
        {
            WriteBaseline(uncovered);
        }

        File.Exists(BaselinePath).ShouldBeTrue(
            $"'{BaselinePath}' is missing. Generate it with {RefreshEnvVar}=1 (see the class remarks).");

        var baseline = ReadBaseline();
        var failures = new List<string>();

        foreach (var name in uncovered.Where(name => !baseline.Contains(name)))
        {
            failures.Add($"+ {name}: a registration entry point that the capability map never names");
        }

        foreach (var name in baseline.Where(name => !uncovered.Contains(name)))
        {
            failures.Add($"- {name}: covered by the capability map now, but still listed in the baseline");
        }

        failures.Sort(StringComparer.Ordinal);

        failures.ShouldBeEmpty(
            customMessage: $"The capability map and the public API disagree.\n" +
                           $"{string.Join('\n', failures)}\n" +
                           $"Add the entry point to {RelativeCapabilityMapPath}, or refresh the baseline: " +
                           $"{RefreshEnvVar}=1 dotnet test tests/Tracon.Core.UnitTests -c Release");
    }

    /// <summary>
    /// Whether the map names the member. The trailing boundary matters:
    /// without it, <c>AddTracon()</c> would silently vouch for a member
    /// called <c>AddAgent</c>.
    /// </summary>
    private static bool IsNamed(string map, string name)
        => Regex.IsMatch(
            map,
            $@"{Regex.Escape(name)}(?![A-Za-z0-9_])",
            RegexOptions.CultureInvariant,
            TimeSpan.FromSeconds(5));

    private static SortedSet<string> ReadBaseline()
    {
        var baseline = new SortedSet<string>(StringComparer.Ordinal);

        foreach (var line in File.ReadLines(BaselinePath))
        {
            if (line.Length > 0 && line[0] != '#')
            {
                baseline.Add(line.Trim());
            }
        }

        return baseline;
    }

    private static void WriteBaseline(IEnumerable<string> uncovered)
    {
        var builder = new StringBuilder();

        builder.Append("# Generated by CapabilityCoverageTests. Refresh:\n");
        builder.Append($"#   {RefreshEnvVar}=1 dotnet test tests/Tracon.Core.UnitTests -c Release\n");
        builder.Append("# One registration entry point per line: allowed to be absent from the capability map.\n");
        builder.Append("# The list may only shrink. An empty list is the intended state.\n");

        foreach (var name in uncovered.OrderBy(name => name, StringComparer.Ordinal))
        {
            builder.Append(name).Append('\n');
        }

        File.WriteAllText(BaselinePath, builder.ToString());
    }

    private const string RelativeCapabilityMapPath = "docs-site/src/content/docs/capabilities.md";

    private static string CapabilityMapPath { get; } =
        Path.Combine(CapabilityEntryPoints.RepositoryRoot, "docs-site", "src", "content", "docs", "capabilities.md");

    private static string BaselinePath { get; } = Path.Combine(
        CapabilityEntryPoints.RepositoryRoot,
        "tests",
        "Tracon.Core.UnitTests",
        "Architecture",
        "capability-coverage-baseline.txt");
}
