using System.Net;
using System.Net.Http.Json;
using Microsoft.Extensions.AI;
using Microsoft.Extensions.DependencyInjection;
using Tracon.AspNetCore.FunctionalTests.Infrastructure;
using FakeModelProvider = Tracon.Testing.FakeModelProvider;

namespace Tracon.AspNetCore.FunctionalTests;

/// <summary>
/// Verifies the optional image-generation endpoint and the agent tool path.
/// </summary>
/// <remarks>
/// The same fake generator is used through both public paths. This proves that
/// generated bytes are stored once as a normal attachment and that a tool
/// invocation records its image quantity rather than returning base64 to the model.
/// </remarks>
#pragma warning disable MEAI001
public sealed class ImageEndpointTests
{
    private static readonly Uri GenerateUri = new("/tracon/api/images/generate", UriKind.Relative);

    [Fact]
    public async Task Endpoint_is_not_mapped_when_images_are_disabled()
    {
        await using var host = await TraconTestHost.StartAsync();

        using var response = await host.Client.PostAsJsonAsync(GenerateUri, new { prompt = "a lighthouse" });

        response.StatusCode.ShouldBe(HttpStatusCode.NotFound);
        host.Services.GetRequiredService<IToolRegistry>().List()
            .ShouldNotContain(tool => string.Equals(tool.Name, "generate_image", StringComparison.Ordinal));
    }

    [Fact]
    public async Task Endpoint_saves_an_attachment_and_returns_configured_cost()
    {
        var generator = new StubImageGenerator();
        await using var host = await StartWithImagesAsync(generator);

        using var response = await host.Client.PostAsJsonAsync(
            GenerateUri,
            new { prompt = "a lighthouse", count = 1, size = "1024x1024", sessionId = "image-session" });

        response.StatusCode.ShouldBe(HttpStatusCode.OK);

        var body = await TraconTestHost.ReadJsonAsync(response);
        var attachment = body.GetProperty("attachments")[0];

        attachment.GetProperty("sessionId").GetString().ShouldBe("image-session");
        attachment.GetProperty("mediaType").GetString().ShouldBe("image/png");
        attachment.GetProperty("id").GetGuid().ShouldNotBe(Guid.Empty);
        body.GetProperty("usage").GetProperty("unit").GetString().ShouldBe(ToolUsageUnits.Images);
        body.GetProperty("usage").GetProperty("quantity").GetDecimal().ShouldBe(1m);
        body.GetProperty("usage").GetProperty("cost").GetDecimal().ShouldBe(0.08m);
        body.GetProperty("usage").GetProperty("currency").GetString().ShouldBe("USD");

        generator.LastRequest.ShouldNotBeNull();
        generator.LastRequest!.Prompt.ShouldBe("a lighthouse");
        generator.LastOptions!.Count.ShouldBe(1);
        generator.LastOptions.ImageSize!.Value.Width.ShouldBe(1024);
        generator.LastOptions.ImageSize!.Value.Height.ShouldBe(1024);

        var attachmentId = attachment.GetProperty("id").GetGuid();
        using var download = await host.Client.GetAsync(
            new Uri($"/tracon/api/attachments/{attachmentId}", UriKind.Relative));

        download.StatusCode.ShouldBe(HttpStatusCode.OK);
        (await download.Content.ReadAsByteArrayAsync()).ShouldBe(Png());
    }

    [Fact]
    public async Task Endpoint_rejects_an_empty_prompt_before_calling_the_provider()
    {
        var generator = new StubImageGenerator();
        await using var host = await StartWithImagesAsync(generator);

        using var response = await host.Client.PostAsJsonAsync(GenerateUri, new { prompt = "  " });

        response.StatusCode.ShouldBe(HttpStatusCode.BadRequest);
        generator.LastRequest.ShouldBeNull();
    }

    [Fact]
    public async Task Endpoint_translates_a_provider_failure_to_bad_gateway()
    {
        // The raw provider message ("provider rejected the request") is a foreign
        // exception's own text and must never reach the client (Phase 119, BL-037):
        // the response carries only the exception's type name and a correlation id.
        var generator = new StubImageGenerator { Exception = new InvalidOperationException("provider rejected the request") };
        await using var host = await StartWithImagesAsync(generator);

        using var response = await host.Client.PostAsJsonAsync(GenerateUri, new { prompt = "a lighthouse" });

        response.StatusCode.ShouldBe(HttpStatusCode.BadGateway);
        var body = await TraconTestHost.ReadJsonAsync(response);
        var detail = body.GetProperty("detail").GetString();
        detail.ShouldNotBeNull();
        detail.ShouldContain("InvalidOperationException");
        detail.ShouldNotContain("provider rejected the request");
    }

    [Fact]
    public async Task Agent_tool_stores_the_image_and_records_image_usage()
    {
        var generator = new StubImageGenerator();
        await using var host = await TraconTestHost.StartAsync(
            builder => builder
                .AddModelProvider(new FakeModelProvider("image-model")
                    .CallsTool("generate_image", new { prompt = "a teal lighthouse" })
                    .EchoesLastToolResult())
                .AddAgent(new AgentDefinition
                {
                    Name = "image-agent",
                    Instructions = "Generate the requested image.",
                    Model = new ModelBinding { Provider = "image-model", Model = "image-1" },
                    ToolNames = ["generate_image"],
                }),
            configureServices: services => ConfigureImages(services, generator));

        using var response = await host.Client.PostAsJsonAsync(
            new Uri("/tracon/api/agents/image-agent/run", UriKind.Relative),
            new AgentRunRequest { Message = "generate an image", SessionId = "tool-image-session" });

        response.StatusCode.ShouldBe(HttpStatusCode.OK);
        await SseReader.ReadAllAsync(await response.Content.ReadAsStreamAsync());

        var run = (await host.Services.GetRequiredService<IRunStore>()
            .QueryRunsAsync(new RunQuery { AgentName = "image-agent" }, TestContext.Current.CancellationToken))
            .ShouldHaveSingleItem();
        var invocation = (await host.Services.GetRequiredService<IRunStore>()
            .ListToolInvocationsAsync(run.Id, TestContext.Current.CancellationToken))
            .ShouldHaveSingleItem();

        invocation.ToolName.ShouldBe("generate_image");
        invocation.Succeeded.ShouldBeTrue();
        invocation.Usage.ShouldNotBeNull();
        invocation.Usage!.Unit.ShouldBe(ToolUsageUnits.Images);
        invocation.Usage.Quantity.ShouldBe(1m);
        invocation.Result.ShouldNotBeNull().ShouldNotContain("iVBOR");

        var attachments = await host.Services.GetRequiredService<IAttachmentStore>()
            .ListAsync(
                new AttachmentQuery { TenantId = "default", SessionId = "tool-image-session" },
                TestContext.Current.CancellationToken);

        attachments.ShouldHaveSingleItem().RunId.ShouldBe(run.Id);
    }

    private static Task<TraconTestHost> StartWithImagesAsync(StubImageGenerator generator)
        => TraconTestHost.StartAsync(configureServices: services => ConfigureImages(services, generator));

    private static void ConfigureImages(IServiceCollection services, StubImageGenerator generator)
    {
        services.Configure<TraconImageOptions>(options =>
        {
            options.Enabled = true;
            options.Provider = "test-images";
            options.Model = "image-1";
            options.MaxImagesPerRequest = 2;
        });
        services.Configure<TraconOptions>(options =>
        {
            options.Pricing.Currency = "USD";
            options.Pricing.Images["test-images"] = new Dictionary<string, ImagePriceOverride>(StringComparer.OrdinalIgnoreCase)
            {
                ["image-1"] = new ImagePriceOverride
                {
                    PerImage = 0.04m,
                    SizeMultipliers = { ["1024x1024"] = 2m },
                },
            };
        });
        services.AddSingleton<IImageGenerator>(generator);
    }

    private static byte[] Png()
    {
        byte[] signature = [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A];
        return [.. signature, .. new byte[8]];
    }

    private sealed class StubImageGenerator : IImageGenerator
    {
        public Exception? Exception { get; init; }

        public ImageGenerationRequest? LastRequest { get; private set; }

        public ImageGenerationOptions? LastOptions { get; private set; }

        public Task<ImageGenerationResponse> GenerateAsync(
            ImageGenerationRequest request,
            ImageGenerationOptions? options = null,
            CancellationToken cancellationToken = default)
        {
            LastRequest = request;
            LastOptions = options;

            if (Exception is { } exception)
            {
                return Task.FromException<ImageGenerationResponse>(exception);
            }

            return Task.FromResult(new ImageGenerationResponse(
                [new DataContent(Png(), "image/png")]));
        }

        public object? GetService(Type serviceType, object? serviceKey = null) => null;

        public void Dispose()
        {
        }
    }
}
#pragma warning restore MEAI001
