using Microsoft.Agents.AI;
using Microsoft.Extensions.AI;

namespace AgentPrism;

/// <summary>
/// Run options that let the caller determine a run's identifier, its place
/// in the tree, and its budget.
/// </summary>
/// <remarks>
/// <para>
/// The wrapper writing the run record normally generates its own identifier
/// and does not report it outward. A streaming endpoint, however, must know
/// the identifier <strong>before the first frame</strong>: only then can the
/// client associate the streamed response with the run record. Having the
/// caller generate the identifier solves this without an extra notification
/// channel or ambient state, and follows the same approach as
/// <see cref="RunStartInfo.RunId"/>.
/// </para>
/// <para>
/// The <see cref="ParentRunId"/>, <see cref="RootRunId"/>, <see cref="Depth"/>,
/// and <see cref="Budget"/> fields are filled in by <c>ChildAgentInvoker</c>
/// when an agent calls another agent. They do not need to be filled in by
/// hand; if they are, the run is placed at the specified spot in the tree.
/// </para>
/// <para>
/// This type <em>carries no</em> <c>ChatOptions</c>. If sampling settings need
/// to change per run, Microsoft Agent Framework's
/// <c>ChatClientAgentRunOptions</c> type is used; the two types cannot be used
/// together. AgentPrism resolves sampling settings from the agent definition
/// on its own endpoints, so this is not a practical constraint.
/// </para>
/// </remarks>
public sealed class AgentPrismRunOptions : AgentRunOptions
{
    /// <summary>Creates a new options object.</summary>
    public AgentPrismRunOptions()
    {
    }

    private AgentPrismRunOptions(AgentPrismRunOptions other)
        : base(other)
    {
        RunId = other.RunId;
        ParentRunId = other.ParentRunId;
        RootRunId = other.RootRunId;
        Depth = other.Depth;
        Budget = other.Budget;
        Kind = other.Kind;
        AgentVersion = other.AgentVersion;
        ExperimentId = other.ExperimentId;
        Variant = other.Variant;
        SessionId = other.SessionId;
        ReplayOfRunId = other.ReplayOfRunId;
    }

    /// <summary>
    /// The run identifier to use. If <see langword="null"/>, the identifier
    /// is generated by the wrapper that writes the run record.
    /// </summary>
    /// <remarks>
    /// The value must be time-ordered; <c>AgentPrismId.NewId()</c> ensures
    /// this. A random identifier produced by <c>Guid.NewGuid()</c> fragments
    /// the storage index.
    /// </remarks>
    public Guid? RunId { get; init; }

    /// <summary>
    /// The identifier of the run that started this run. <see langword="null"/>
    /// for the root run.
    /// </summary>
    public Guid? ParentRunId { get; init; }

    /// <summary>
    /// The identifier of the run at the root of the tree. <see langword="null"/> if the
    /// run itself is the root.
    /// </summary>
    /// <remarks>
    /// The value is denormalized: fetching a whole tree through <see
    /// cref="ParentRunId"/> would require a recursive query; a single indexed query on
    /// the root identifier is enough.
    /// </remarks>
    public Guid? RootRunId { get; init; }

    /// <summary>The depth in the tree. The root run is 0.</summary>
    public int Depth { get; init; }

    /// <summary>
    /// The budget <strong>shared</strong> across the tree. If
    /// <see langword="null"/>, the wrapper opening the root run produces a
    /// budget from its settings.
    /// </summary>
    /// <remarks>
    /// The object is the <em>same instance</em> at every run in the tree. If
    /// it were copied, each branch would get its own budget and the limit
    /// would lose its meaning.
    /// </remarks>
    public AgentRunBudget? Budget { get; init; }

    /// <summary>
    /// This run's kind. If <see langword="null"/>, the wrapper assumes
    /// <see cref="RunKind.Agent"/>.
    /// </summary>
    /// <remarks>
    /// The eval job processor gives <see cref="RunKind.Eval"/> for
    /// every case run; this lets <see cref="IRunStore.GetStatisticsAsync"/>
    /// exclude these synthetic calls from the summary.
    /// </remarks>
    public RunKind? Kind { get; init; }

    /// <summary>
    /// The definition version this run measures. If <see langword="null"/>,
    /// the wrapper uses the (current) version from the agent's catalog
    /// summary. For runs resolved by an A/B experiment, this field is
    /// filled in because the compiled agent's <em>actual</em> version may
    /// differ from the current one.
    /// </summary>
    public int? AgentVersion { get; init; }

    /// <summary>The identifier of the experiment this run belongs to. <see langword="null"/> for a non-experiment run.</summary>
    public Guid? ExperimentId { get; init; }

    /// <summary>
    /// The name of the experiment variant this run is assigned to. <see
    /// langword="null"/> for a non-experiment run.
    /// </summary>
    public string? Variant { get; init; }

    /// <summary>
    /// The identifier of the session at the root of the tree. Filled in for child runs;
    /// the root run reads its identifier from its own <c>AgentSession</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This field only feeds <c>AgentRunScope.SessionId</c>; it <strong>does not
    /// change</strong> a run record's <c>session_id</c> column. The two concepts are
    /// separate: the column says "the run was started with this session," while the
    /// scope says "content produced here belongs to this session." On a child agent
    /// call, MAF passes no session, but the produced attachment still belongs to the
    /// root session.
    /// </para>
    /// <para>
    /// This matters for retention: an attachment written without a session counts as
    /// orphaned, and the retention policy deletes it.
    /// </para>
    /// </remarks>
    public string? SessionId { get; init; }

    /// <summary>
    /// If this run is a replay, the source run's identifier. The
    /// value is written to the <c>runs.replay_of_run_id</c> column.
    /// </summary>
    /// <remarks>
    /// This field is meaningful only for the <strong>root</strong> run; a
    /// replay's child calls do not carry their own lineage.
    /// </remarks>
    public Guid? ReplayOfRunId { get; init; }

    /// <summary>
    /// Gets the work that must be DONE AND VISIBLE before the run is closed with
    /// <see cref="RunStatus.AwaitingApproval"/>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <see cref="RunStatus.AwaitingApproval"/> is TERMINAL and is the signal a
    /// consumer polls on. Whoever records the pending approval does so AFTER the
    /// agent call returns — but the run is closed INSIDE that call, so without this
    /// hook the status is published first and <c>GET /api/approvals/pending</c>
    /// answers an empty list for a run that already says it is waiting. The window
    /// was not a race: the order was fixed, so it was open on EVERY such run.
    /// </para>
    /// <para>
    /// The callback receives the messages the run produced and runs on BOTH the
    /// buffered and the streaming path, immediately before the terminal status is
    /// written. It runs only when the run actually ends by requesting approval;
    /// anything it throws fails the run, which is correct — a published
    /// <see cref="RunStatus.AwaitingApproval"/> whose approval was never recorded
    /// is unanswerable.
    /// </para>
    /// </remarks>
    public Func<IEnumerable<ChatMessage>, CancellationToken, ValueTask>? BeforePendingApprovalIsPublished { get; init; }

    /// <inheritdoc />
    /// <remarks>
    /// Cloning preserves all fields. Otherwise, a middleware layer copying
    /// the options would silently drop the identifier, and the wrapper would
    /// generate its own — the identifier reported to the client would then
    /// correspond to no record at all. The same trap is more insidious for
    /// the tree fields: a dropped <see cref="Depth"/> value silently disables
    /// recursion protection.
    /// </remarks>
    public override AgentRunOptions Clone() => new AgentPrismRunOptions(this);
}
