using System.Text.Json.Serialization;

namespace AgentPrism;

/// <summary>
/// The summary of a single completed tool call.
/// </summary>
/// <remarks>
/// <para>
/// This record is a <em>projection</em> of the event stream: the same
/// information also exists in the <see cref="RunEventType.ToolInvoking"/> and
/// <see cref="RunEventType.ToolInvoked"/> events. It is kept in a separate
/// table so that <see cref="Duration"/> and per-tool totals can be queried
/// without scanning the whole event stream.
/// </para>
/// <para>
/// The record is written only when the call <strong>settles</strong>; its
/// duration is computed from correlating the <c>ToolInvoking</c> and
/// <c>ToolInvoked</c> event pair.
/// </para>
/// </remarks>
public sealed record ToolInvocationRecord
{
    /// <summary>The record identifier. A time-ordered UUID (v7).</summary>
    public required Guid Id { get; init; }

    /// <summary>The run that made the call.</summary>
    public required Guid RunId { get; init; }

    /// <summary>The name of the tool called.</summary>
    public required string ToolName { get; init; }

    /// <summary>The call identifier generated by the model. Distinguishes multiple calls of the same kind.</summary>
    public string? ToolCallId { get; init; }

    /// <summary>
    /// The tool's source. <see langword="null"/> for tools defined in code;
    /// the server name for MCP tools.
    /// </summary>
    public string? Source { get; init; }

    /// <summary>The call arguments. Raw text; may not be valid JSON.</summary>
    public string? Arguments { get; init; }

    /// <summary>The call result. Raw text; may not be valid JSON.</summary>
    public string? Result { get; init; }

    /// <summary>The call's duration. <see langword="null"/> if the event pair did not match.</summary>
    public TimeSpan? Duration { get; init; }

    /// <summary>The error message. Populated only if the call errored.</summary>
    public string? Error { get; init; }

    /// <summary>The moment the call settled (UTC).</summary>
    public required DateTimeOffset CreatedAt { get; init; }

    /// <summary>
    /// The call's non-token measurement and cost. <see langword="null"/> if
    /// the tool reported no measurement — which is empty for the vast
    /// majority of calls.
    /// </summary>
    /// <remarks>
    /// The value is reported by the tool's own body with
    /// <c>AgentPrismToolUsage.Report(...)</c> and linked to this record by the
    /// call identifier. See <c>docs/28-SES-TOOLLARI.md</c>, section 28.5, for the rationale.
    /// </remarks>
    public ToolCallUsage? Usage { get; init; }

    /// <summary>
    /// The EXPECTED tenant of the run that made the call. Defense in depth;
    /// if <see langword="null"/>, no tenant check is performed.
    /// </summary>
    /// <remarks>
    /// <para>
    /// See <see cref="RunEvent.TenantId"/> for the rationale and why the
    /// ambient tenant is not used. Decision K-355.
    /// </para>
    /// <para>
    /// 🚨 This field is WRITE-SIDE ONLY: it is not written to a column, it is
    /// only used as the write's <c>WHERE</c> guard. It would always be
    /// <see langword="null"/> when read back, so it is excluded from the HTTP
    /// contract with <see cref="JsonIgnoreAttribute"/>. Otherwise the OpenAPI
    /// document would declare a field that never gets populated.
    /// </para>
    /// </remarks>
    [JsonIgnore]
    public string? TenantId { get; init; }

    /// <summary>Whether the call finished successfully.</summary>
    public bool Succeeded => Error is null;
}

/// <summary>The filter for a tool usage summary.</summary>
public sealed record ToolUsageQuery
{
    /// <summary>The tenant filter. The current tenant is used if left empty.</summary>
    public string? TenantId { get; init; }

    /// <summary>Count only calls from runs that started after this moment.</summary>
    public DateTimeOffset? StartedAfter { get; init; }

    /// <summary>The maximum number of tools to return. Tools with the highest call count are returned first.</summary>
    public int MaxTools { get; init; } = 50;
}

/// <summary>A tool's usage summary. Shown by the UI's Tools screen.</summary>
public sealed record ToolUsage
{
    /// <summary>The tool name.</summary>
    public required string ToolName { get; init; }

    /// <summary>The total number of calls.</summary>
    public required long TotalCalls { get; init; }

    /// <summary>The number of calls that errored.</summary>
    public required long FailedCalls { get; init; }

    /// <summary>The average duration (milliseconds). <see langword="null"/> if no call carries a duration.</summary>
    public double? AverageDurationMs { get; init; }

    /// <summary>The moment it was last called (UTC).</summary>
    public DateTimeOffset? LastCalledAt { get; init; }

    /// <summary>
    /// The error rate among settled calls (0–1). <see langword="null"/> if there is no call.
    /// </summary>
    public double? ErrorRate => TotalCalls == 0 ? null : (double)FailedCalls / TotalCalls;
}
