using Microsoft.Agents.AI.Workflows;

namespace AgentPrism;

/// <summary>
/// Extracts the graph the UI can draw from a compiled <see cref="Workflow"/>.
/// </summary>
/// <remarks>
/// <para>
/// The extraction relies on Microsoft Agent Framework's three reflection
/// methods: <c>ReflectExecutors()</c> gives the nodes, <c>ReflectEdges()</c>
/// the edges, <c>ReflectPorts()</c> the external request ports.
/// <c>WorkflowVisualizer</c> also produces a ready-made Mermaid string; that
/// string is <em>not rendered</em> in the UI, it is only exported - rendering
/// Mermaid in the browser costs ~100 KB gzipped and the bundle budget is
/// 250 KB.
/// </para>
/// <para>
/// Node ids are kept <strong>identical</strong> to the executor ids in run
/// events; this is how the UI colors nodes live. Labels are shortened, but
/// the id is never altered.
/// </para>
/// </remarks>
internal static class WorkflowGraphReader
{
    /// <summary>Extracts the graph.</summary>
    /// <param name="name">The workflow name.</param>
    /// <param name="workflow">The compiled graph.</param>
    /// <returns>The graph to send to the UI.</returns>
    public static WorkflowGraph Read(string name, Workflow workflow)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        ArgumentNullException.ThrowIfNull(workflow);

        var executors = workflow.ReflectExecutors();
        var ports = workflow.ReflectPorts();

        var nodes = new List<WorkflowGraphNode>(executors.Count);

        foreach (var (id, binding) in executors)
        {
            var isPort = ports.ContainsKey(id);
            var agentName = AgentNameOf(binding, id);

            nodes.Add(new WorkflowGraphNode
            {
                Id = id,
                Label = agentName ?? Shorten(id),
                Kind = Classify(binding, isPort, agentName),
                AgentName = agentName,
                ExecutorType = binding.ExecutorType.Name,
            });
        }

        var edges = new List<WorkflowGraphEdge>();

        foreach (var (source, connections) in workflow.ReflectEdges())
        {
            foreach (var edge in connections)
            {
                foreach (var sink in edge.Connection.SinkIds)
                {
                    edges.Add(new WorkflowGraphEdge
                    {
                        From = source,
                        To = sink,
                        Kind = Map(edge.Kind),
                    });
                }
            }
        }

        return new WorkflowGraph
        {
            Name = name,
            StartExecutorId = workflow.StartExecutorId,
            Nodes = [.. nodes.OrderBy(static node => node.Id, StringComparer.Ordinal)],
            Edges = [.. edges.OrderBy(static edge => edge.From, StringComparer.Ordinal)
                             .ThenBy(static edge => edge.To, StringComparer.Ordinal)],
            Mermaid = WorkflowVisualizer.ToMermaidString(workflow),
        };
    }

    /// <summary>Extracts the name of the agent a node represents.</summary>
    /// <remarks>
    /// A bound agent is carried directly by <see cref="AIAgentBinding"/>. The
    /// Handoff pattern wraps the agent in its own executor, so it cannot be
    /// read from the binding type; in that case the identity is parsed from
    /// the <c>{name}_{id}</c> form. Because the id portion is generated by
    /// AgentPrism (32 hex characters), the parsing does not rely on guesswork.
    /// </remarks>
    private static string? AgentNameOf(ExecutorBinding binding, string id)
    {
        if (binding is AIAgentBinding agent)
        {
            return agent.Agent.Name;
        }

        // An agent step inside a mixed Sequential chain (phase 71) is bound
        // as a WorkflowAgentStepExecutor, not an AIAgentBinding, so there is
        // no Agent property to read - but WorkflowDefinitionCompiler always
        // sets its id to the agent's own catalog name, so the id already IS
        // the answer.
        if (binding.ExecutorType.Name.Equals(nameof(WorkflowAgentStepExecutor), StringComparison.Ordinal))
        {
            return id;
        }

        // 🚨 Composite ids are not parsed. Measured (phase 16): the `Concurrent`
        // pattern adds a `Batcher/{name}_{id}` node for every agent, and the
        // trailing id fragment has the same format; without checking for the
        // slash, the aggregator node would be mistaken for an agent and the
        // graph would show every agent twice.
        if (id.Contains('/', StringComparison.Ordinal))
        {
            return null;
        }

        var separator = id.LastIndexOf('_');

        if (separator <= 0 || id.Length - separator - 1 != 32)
        {
            return null;
        }

        for (var index = separator + 1; index < id.Length; index++)
        {
            if (!Uri.IsHexDigit(id[index]))
            {
                return null;
            }
        }

        return id[..separator];
    }

    private static WorkflowNodeKind Classify(ExecutorBinding binding, bool isPort, string? agentName)
    {
        if (isPort || binding is RequestPortBinding)
        {
            return WorkflowNodeKind.RequestPort;
        }

        if (agentName is not null)
        {
            return WorkflowNodeKind.Agent;
        }

        // A registered code function (phase 71). The bound type is literally
        // FunctionExecutor<TInput,TOutput> - reflected as "FunctionExecutor`2"
        // - so this is a reliable signal, unlike guessing from the node id.
        if (binding.ExecutorType.Name.StartsWith("FunctionExecutor", StringComparison.Ordinal))
        {
            return WorkflowNodeKind.Function;
        }

        // Output nodes are appended at the end of the ready-made patterns and
        // collect the graph's result; the UI draws them with a distinct shape.
        return binding.ExecutorType.Name.Contains("Output", StringComparison.Ordinal)
            ? WorkflowNodeKind.Output
            : WorkflowNodeKind.Orchestration;
    }

    private static WorkflowEdgeKind Map(EdgeKind kind) => kind switch
    {
        EdgeKind.FanOut => WorkflowEdgeKind.FanOut,
        EdgeKind.FanIn => WorkflowEdgeKind.FanIn,
        _ => WorkflowEdgeKind.Direct,
    };

    /// <summary>Shortens a long executor id into a readable label.</summary>
    private static string Shorten(string id)
    {
        var slash = id.LastIndexOf('/');

        return slash >= 0 && slash < id.Length - 1 ? id[(slash + 1)..] : id;
    }
}
