#!/usr/bin/env python3
"""Generates the JsonSerializerContext AgentPrism.Client needs for AOT.

The NSwag-generated client (src/AgentPrism.Client/Generated/AgentPrismApiClient.g.cs)
calls System.Text.Json.JsonSerializer.Deserialize<T>/SerializeToUtf8Bytes<T>
with a JsonSerializerOptions whose TypeInfoResolver we plug a source-generated
JsonSerializerContext into (docs/arsiv/fazlar/83-TIPLI-ISTEMCI-VE-CLI.md, section 83.6).
Source generation propagates to every type reachable from a declared root's
public properties automatically, so this script only needs to find the ROOT
types: every T passed to ReadObjectResponseAsync<T> (response bodies, success
and error) and every request body parameter type.

Usage: generate-client-json-context.py <generated-client.cs> <output.cs>
"""

import re
import sys

READ_RESPONSE_RE = re.compile(r"ReadObjectResponseAsync<(.+?)>\(")
BODY_PARAM_RE = re.compile(r"([\w.]+(?:<[^<>]*>)?)\s+body[,)]")
VALID_ROOT_RE = re.compile(r"^[A-Za-z_][\w.]*(?:<[A-Za-z_][\w.]*>)?$")

# Primitive / BCL types the source generator already knows about via its own
# built-in converters (listing them as [JsonSerializable] is either invalid or
# redundant), plus "T": the generic placeholder in the client's own
# ReadObjectResponseAsync<T> method DEFINITION, which the regex above also
# matches since it looks exactly like a call.
SKIP_ROOTS = {"string", "bool", "int", "long", "double", "object", "T"}

HEADER = """// <auto-generated>
//     Generated by scripts/generate-client-json-context.py from
//     AgentPrismApiClient.g.cs. Re-run after every `dotnet nswag run nswag.json`.
// </auto-generated>

using System.Text.Json.Serialization;

namespace AgentPrism.Client.Generated;

/// <summary>
/// Source-generated type metadata for every request/response type the
/// generated client serializes. Wired into
/// <see cref="System.Text.Json.JsonSerializerOptions.TypeInfoResolver"/> by
/// <c>AgentPrismApiClient.JsonContext.cs</c> instead of runtime reflection.
/// </summary>
/// <remarks>
/// Every enum's own <c>[JsonConverter(typeof(JsonStringEnumConverter{{T}}))]</c>
/// (added directly on the <c>enum</c> declaration by
/// <c>nswag-postprocess-client.py</c>) is what makes it travel as its name,
/// not its ordinal, matching the server's wire format - registering the
/// converter here instead, through <c>[JsonSourceGenerationOptions.Converters]</c>,
/// was tried first and measured NOT to take effect for enum types only
/// reachable through a property.
/// </remarks>
[JsonSourceGenerationOptions(PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase)]
{attributes}
internal sealed partial class AgentPrismClientJsonContext : JsonSerializerContext
{{
}}
"""


def main() -> int:
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <generated-client.cs> <output.cs>", file=sys.stderr)
        return 1

    input_path, output_path = sys.argv[1], sys.argv[2]

    with open(input_path, encoding="utf-8") as f:
        lines = f.readlines()

    # Drop XML doc-comment lines: prose like "the response body, headers, or
    # ..." reads as a false body-parameter match otherwise.
    code_only = "\n".join(line for line in lines if not line.strip().startswith("///"))

    roots = set()
    for match in READ_RESPONSE_RE.finditer(code_only):
        roots.add(match.group(1).strip())
    for match in BODY_PARAM_RE.finditer(code_only):
        roots.add(match.group(1).strip())

    roots = {r for r in roots if r not in SKIP_ROOTS}

    invalid = sorted(r for r in roots if not VALID_ROOT_RE.match(r))
    if invalid:
        raise SystemExit(
            "Extraction produced type names that do not look like real C# types "
            f"(regex needs a fix): {invalid}"
        )

    ordered = sorted(roots)

    attributes = "\n".join(f"[JsonSerializable(typeof({t}))]" for t in ordered)

    with open(output_path, "w", encoding="utf-8") as f:
        f.write(HEADER.format(attributes=attributes))

    print(f"Registered {len(ordered)} root types -> {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
