#!/usr/bin/env bash
#
# Builds docs-site/ and publishes it to the server that hosts it.
#
# The site is a separate publication pipeline: it is not part of `dotnet build`
# and never enters a package. It does need the .NET build, because the API
# reference is generated by DocFX from the compiled assemblies and their XML
# documentation - run this after a build and you get the previous version's text.
#
# Every gate runs before anything is copied. `set -e` is what enforces that: a red
# gate ends the script and rsync is never reached.
#
# Usage:
#   scripts/site-deploy.sh              build, check, publish
#   scripts/site-deploy.sh --dry-run    build, check, show what would change
#
# Overridable:
#   SITE_HOST      ssh destination            (default root@167.172.168.49)
#   SITE_PATH      document root on the host  (default /var/www/agentprism)
#   SITE_STACK     compose directory on host  (default /deploy/agentprism)
#   SITE_SSH_KEY   private key                (default ~/.ssh/id_ed25519_digitalocean)

set -euo pipefail

SITE_HOST="${SITE_HOST:-root@167.172.168.49}"
SITE_PATH="${SITE_PATH:-/var/www/agentprism}"
SITE_STACK="${SITE_STACK:-/deploy/agentprism}"
SITE_SSH_KEY="${SITE_SSH_KEY:-$HOME/.ssh/id_ed25519_digitalocean}"

repository_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repository_root"

dry_run=""
if [[ "${1:-}" == "--dry-run" ]]; then
  dry_run="--dry-run"
elif [[ -n "${1:-}" ]]; then
  echo "unknown argument: $1" >&2
  exit 2
fi

# --delete removes anything on the host that the build did not produce. Pointed at
# the wrong directory that is data loss, so refuse a path shallow enough to be a
# mistake rather than a target.
if [[ "$(tr -cd '/' <<<"$SITE_PATH" | wc -c)" -lt 2 || "$SITE_PATH" == */ ]]; then
  echo "SITE_PATH must be a nested path without a trailing slash; got '$SITE_PATH'" >&2
  exit 2
fi

ssh_command=(ssh -i "$SITE_SSH_KEY" -o IdentitiesOnly=yes -o BatchMode=yes -o ConnectTimeout=10)

step() { printf '\n\033[1m==> %s\033[0m\n' "$1"; }

# The one declaration of the published address, read rather than repeated.
site_host() {
  node --input-type=module -e \
    "import { site } from './docs-site/site.config.mjs'; process.stdout.write(new URL(site).host);"
}

# Before the build, not after: the build takes minutes and an unreachable host or a
# missing document root is worth learning in the first second.
step "Checking $SITE_HOST"
"${ssh_command[@]}" "$SITE_HOST" "mkdir -p '$SITE_PATH' '$SITE_STACK'" || {
  echo "cannot reach $SITE_HOST." >&2
  echo >&2
  echo "This script authenticates by key only (BatchMode); a password prompt cannot" >&2
  echo "be answered from an unattended run. Authorize the key once:" >&2
  echo "  ssh-copy-id -i ${SITE_SSH_KEY}.pub $SITE_HOST" >&2
  exit 1
}

# The console assets are not part of the documentation site, and building them
# would add the whole npm/Vite chain to a run that has no use for it.
step "Building the solution (DocFX reads its output)"
dotnet build AgentPrism.slnx -c Release -p:AgentPrismFrontendEnabled=false

step "Restoring DocFX"
dotnet tool restore

# `npm ci` deletes node_modules and reinstalls it, which measured 75 s of a 137 s
# run and reproduces the identical tree when the lockfile has not moved. npm records
# the tree it installed in node_modules/.package-lock.json, so comparing the two is
# an honest test of "is the install current" rather than a guess.
if [[ ! -f docs-site/node_modules/.package-lock.json ]] \
  || [[ docs-site/package-lock.json -nt docs-site/node_modules/.package-lock.json ]]; then
  step "Installing site dependencies"
  npm --prefix docs-site ci
else
  step "Site dependencies are current (lockfile unchanged)"
fi

# All four gates, in one command. `npm run build` alone is not enough: it skips the
# content gate before it and the link and weight gates after it.
step "Generating, building, and checking the site"
npm --prefix docs-site run check

# The serving stack lives in the repository, not by hand on the host: an nginx
# container behind the Traefik that already owns :80 and :443 there. `.env` is
# written here rather than committed so the address keeps exactly one declaration.
step "Publishing the serving stack to $SITE_HOST:$SITE_STACK"
env_file="$(mktemp)"
trap 'rm -f "$env_file"' EXIT
printf 'SITE_HOST=%s\n' "$(site_host)" >"$env_file"

rsync -az ${dry_run:+"$dry_run"} \
  -e "${ssh_command[*]}" \
  docs-site/deploy/docker-compose.yml docs-site/deploy/nginx.conf \
  "$SITE_HOST:$SITE_STACK/"

rsync -az ${dry_run:+"$dry_run"} \
  -e "${ssh_command[*]}" \
  "$env_file" "$SITE_HOST:$SITE_STACK/.env"

# rsync cannot set the mode portably here: macOS ships openrsync, which rejects
# --chmod. The file holds no secret today, but it is configuration for a service.
if [[ -z "$dry_run" ]]; then
  "${ssh_command[@]}" "$SITE_HOST" "chmod 600 '$SITE_STACK/.env'"
fi

step "Publishing the site to $SITE_HOST:$SITE_PATH"
rsync -az --delete ${dry_run:+"$dry_run"} \
  -e "${ssh_command[*]}" \
  docs-site/dist/ "$SITE_HOST:$SITE_PATH/"

# Idempotent: no output beyond "Running" when nothing changed. It is here so the
# container can never drift from the compose file in the repository.
if [[ -z "$dry_run" ]]; then
  step "Reconciling the container"
  "${ssh_command[@]}" "$SITE_HOST" "cd '$SITE_STACK' && docker compose up -d"
fi

if [[ -n "$dry_run" ]]; then
  printf '\nDry run: nothing was published.\n'
else
  printf '\nPublished. Verify:\n'
  printf '  curl -sI https://agentprism.doayen.web.tr/ | head -1\n'
  printf '  curl -sI https://doayen.web.tr/ | head -1   # the app at the apex, untouched\n'
fi
