using System.Text.Json;

namespace AgentPrism;

/// <summary>
/// Performs <em>shallow</em> validation of script arguments against declared JSON Schema.
/// </summary>
/// <remarks>
/// <para>
/// Validation is intentionally limited to the root object, fields in the
/// <c>required</c> list, and top-level types of fields under <c>properties</c>.
/// It does <strong>not</strong> validate nested schema, <c>oneOf</c>, <c>pattern</c>,
/// or similar rules.
/// </para>
/// <para>
/// A complete JSON Schema validator would require another NuGet dependency. AgentPrism
/// is a library, so adding a package to the consumer dependency graph only to limit
/// arguments is not appropriate. The real security boundary limits the process and environment, not argument schema.
/// </para>
/// </remarks>
internal static class SkillScriptArgumentValidator
{
    /// <summary>Validates arguments and returns the reason when they are not valid.</summary>
    /// <param name="schema">The JSON Schema object. Validation is skipped when it is <see langword="null"/>.</param>
    /// <param name="arguments">The arguments generated by the model.</param>
    /// <param name="error">The error reason when validation fails.</param>
    /// <returns><see langword="true"/> when the arguments are valid.</returns>
    public static bool TryValidate(JsonElement? schema, JsonElement? arguments, out string? error)
    {
        error = null;

        if (schema is not { ValueKind: JsonValueKind.Object } schemaElement)
        {
            return true;
        }

        if (arguments is not { } argumentsElement || argumentsElement.ValueKind == JsonValueKind.Null)
        {
            argumentsElement = default;
        }

        if (argumentsElement.ValueKind is not (JsonValueKind.Object or JsonValueKind.Undefined))
        {
            error = "Script arguments must be a JSON object.";
            return false;
        }

        if (schemaElement.TryGetProperty("required", out var required) &&
            required.ValueKind == JsonValueKind.Array)
        {
            foreach (var item in required.EnumerateArray())
            {
                if (item.ValueKind != JsonValueKind.String)
                {
                    continue;
                }

                var name = item.GetString()!;

                if (argumentsElement.ValueKind == JsonValueKind.Undefined ||
                    !argumentsElement.TryGetProperty(name, out _))
                {
                    error = $"Required argument '{name}' is missing.";
                    return false;
                }
            }
        }

        if (argumentsElement.ValueKind == JsonValueKind.Undefined ||
            !schemaElement.TryGetProperty("properties", out var properties) ||
            properties.ValueKind != JsonValueKind.Object)
        {
            return true;
        }

        foreach (var property in argumentsElement.EnumerateObject())
        {
            if (!properties.TryGetProperty(property.Name, out var propertySchema) ||
                propertySchema.ValueKind != JsonValueKind.Object ||
                !propertySchema.TryGetProperty("type", out var type) ||
                type.ValueKind != JsonValueKind.String)
            {
                continue;
            }

            if (!Matches(type.GetString(), property.Value.ValueKind))
            {
                error = $"Argument '{property.Name}' must have type '{type.GetString()}'.";
                return false;
            }
        }

        return true;
    }

    private static bool Matches(string? type, JsonValueKind kind) => type switch
    {
        "string" => kind == JsonValueKind.String,
        "number" or "integer" => kind == JsonValueKind.Number,
        "boolean" => kind is JsonValueKind.True or JsonValueKind.False,
        "object" => kind == JsonValueKind.Object,
        "array" => kind == JsonValueKind.Array,
        "null" => kind == JsonValueKind.Null,
        _ => true,
    };
}
