using System.Text;

namespace AgentPrism.Generators;

/// <summary>
/// <see cref="ToolEmitModel"/>'den bicimli (dotnet format uyumlu), <auto-generated/>
/// basligi tasiyan C# kaynagi uretir.
/// </summary>
internal static class SourceWriter
{
    private const string Header = "// <auto-generated/>\n#nullable enable\n\n";

    /// <summary>Bir tool icin <c>AIFunction</c> turevi sarmalayici sinifi uretir.</summary>
    public static string WriteToolWrapper(ToolEmitModel model)
    {
        var sb = new StringBuilder(Header);

        sb.Append("namespace AgentPrism.Generated;\n\n");
        sb.Append("/// <summary>Uretilen tool sarmalayicisi: ")
          .Append(model.ContainingTypeDisplay).Append('.').Append(model.MethodName)
          .Append(".</summary>\n");
        sb.Append("internal sealed class ").Append(model.GeneratedClassName).Append(" : global::Microsoft.Extensions.AI.AIFunction\n{\n");

        sb.Append("    private static readonly global::System.Text.Json.JsonDocument SchemaDocument =\n")
          .Append("        global::System.Text.Json.JsonDocument.Parse(")
          .Append(ToStringLiteral(BuildSchema(model.Parameters)))
          .Append(");\n\n");

        sb.Append("    public override string Name => ").Append(ToStringLiteral(model.ToolName)).Append(";\n\n");
        // AITool.Description'in NRT imzasi NON-nullable string'dir (olculdu: CS8764,
        // Microsoft.Extensions.AI.Abstractions 10.8.3). Aciklama yoksa (APG0006
        // zaten uyarir) bos dize donulur - null DEGIL.
        sb.Append("    public override string Description => ")
          .Append(ToStringLiteral(model.Description ?? string.Empty))
          .Append(";\n\n");
        sb.Append("    public override global::System.Text.Json.JsonElement JsonSchema => SchemaDocument.RootElement;\n\n");

        sb.Append("    protected override ");
        sb.Append(RequiresAwait(model.Return) ? "async " : string.Empty);
        sb.Append("global::System.Threading.Tasks.ValueTask<object?> InvokeCoreAsync(\n")
          .Append("        global::Microsoft.Extensions.AI.AIFunctionArguments arguments,\n")
          .Append("        global::System.Threading.CancellationToken cancellationToken)\n    {\n");

        var callArguments = new List<string>();

        foreach (var parameter in model.Parameters)
        {
            if (parameter.Shape == ParameterShape.CancellationToken)
            {
                callArguments.Add("cancellationToken");
                continue;
            }

            var variableName = "@" + parameter.Name;
            sb.Append("        var ").Append(variableName).Append(" = ").Append(WriteBinding(parameter)).Append(";\n");
            callArguments.Add(variableName);
        }

        // ContainingTypeDisplay zaten "global::..." ile baslar (FullyQualifiedFormat).
        var invocation = $"{model.ContainingTypeDisplay}.{model.MethodName}({string.Join(", ", callArguments)})";

        switch (model.Return)
        {
            case ReturnKind.None:
                sb.Append("        ").Append(invocation).Append(";\n");
                sb.Append("        return new global::System.Threading.Tasks.ValueTask<object?>(result: null);\n");
                break;
            case ReturnKind.Value:
                sb.Append("        var result = ").Append(invocation).Append(";\n");
                sb.Append("        return new global::System.Threading.Tasks.ValueTask<object?>((object?)result);\n");
                break;
            case ReturnKind.AsyncNone:
                sb.Append("        await ").Append(invocation).Append(".ConfigureAwait(false);\n");
                sb.Append("        return null;\n");
                break;
            case ReturnKind.AsyncValue:
                sb.Append("        var result = await ").Append(invocation).Append(".ConfigureAwait(false);\n");
                sb.Append("        return (object?)result;\n");
                break;
        }

        sb.Append("    }\n}\n");

        return sb.ToString();
    }

    /// <summary>Tum tool kayitlarini toplayan giris noktasini ve <c>AddGeneratedTools()</c> uzantisini uretir.</summary>
    public static string WriteAggregator(IReadOnlyList<ToolEmitModel> tools)
    {
        var sb = new StringBuilder(Header);

        sb.Append("using global::Microsoft.Extensions.DependencyInjection;\n\n");

        // Dosya-kapsamli (`namespace X;`) bicim dosya basina TEK ad alani ile
        // sinirlidir (CS8954); iki ad alani gerektigi icin BLOK bicimi kullanilir.
        sb.Append("namespace AgentPrism.Generated\n{\n");
        sb.Append("    /// <summary>Kaynak ureteci tarafindan bulunan tum tool kayitlari.</summary>\n");
        sb.Append("    internal static class AgentPrismGeneratedTools\n    {\n");
        sb.Append("        /// <summary>Bu derlemedeki tum uretilen tool kayitlarini olusturur.</summary>\n");
        sb.Append("        public static global::System.Collections.Generic.IReadOnlyList<global::AgentPrism.AgentPrismToolRegistration> Create()\n");
        sb.Append("            => new global::AgentPrism.AgentPrismToolRegistration[]\n            {\n");

        foreach (var model in tools)
        {
            sb.Append("                new(new ").Append(model.GeneratedClassName).Append("(), requiresApproval: ")
              .Append(model.RequiresApproval ? "true" : "false")
              .Append(", source: \"generated\"),\n");
        }

        sb.Append("            };\n    }\n}\n\n");

        sb.Append("namespace AgentPrism\n{\n");
        sb.Append("    /// <summary>Kaynak ureteci tarafindan bulunan tool kayitlarini <see cref=\"IAgentPrismBuilder\"/>'a ekler.</summary>\n");
        sb.Append("    public static class AgentPrismGeneratedToolsBuilderExtensions\n    {\n");
        sb.Append("        /// <summary>\n");
        sb.Append("        /// Bu derlemedeki <c>[AgentPrismTool]</c> ile isaretli tum metotlari, yansima\n");
        sb.Append("        /// KULLANMADAN kaydeder. Baska bir derlemedeki tool'lar icin <c>AddToolsFrom</c> kullanin.\n");
        sb.Append("        /// </summary>\n");
        sb.Append("        /// <param name=\"builder\">AgentPrism yapilandirma zinciri.</param>\n");
        sb.Append("        /// <returns>Zincirin devami.</returns>\n");
        sb.Append("        public static global::AgentPrism.IAgentPrismBuilder AddGeneratedTools(this global::AgentPrism.IAgentPrismBuilder builder)\n        {\n");
        sb.Append("            global::System.ArgumentNullException.ThrowIfNull(builder);\n\n");
        sb.Append("            foreach (var registration in global::AgentPrism.Generated.AgentPrismGeneratedTools.Create())\n            {\n");
        sb.Append("                builder.Services.AddSingleton(registration);\n");
        sb.Append("            }\n\n");
        sb.Append("            return builder;\n        }\n    }\n}\n");

        return sb.ToString();
    }

    private static bool RequiresAwait(ReturnKind kind) => kind is ReturnKind.AsyncNone or ReturnKind.AsyncValue;

    private static string WriteBinding(ParameterModel parameter)
    {
        var nameLiteral = ToStringLiteral(parameter.Name);

        if (parameter.Shape == ParameterShape.Array)
        {
            var elementConverter = WriteElementConverter(parameter.Leaf!);
            var required = parameter.IsRequired ? "true" : "false";
            var defaultValue = parameter.IsRequired ? "null" : (parameter.DefaultValueLiteral ?? "null");

            return $"global::AgentPrism.AgentPrismGeneratedToolArguments.GetArray(arguments, {nameLiteral}, static e => {elementConverter}, required: {required}, defaultValue: {defaultValue})";
        }

        var converter = WriteElementConverter(parameter.Leaf!);

        return parameter.IsRequired
            ? $"global::AgentPrism.AgentPrismGeneratedToolArguments.GetRequired(arguments, {nameLiteral}, static e => {converter})"
            : $"global::AgentPrism.AgentPrismGeneratedToolArguments.GetOptional(arguments, {nameLiteral}, static e => {converter}, {parameter.DefaultValueLiteral ?? "default"})";
    }

    private static string WriteElementConverter(LeafType leaf)
    {
        var inner = WriteNonNullConverter(leaf);

        if (!leaf.IsNullable)
        {
            return inner;
        }

        return $"e.ValueKind == global::System.Text.Json.JsonValueKind.Null ? ({leaf.ClrTypeDisplay}?)null : ({inner})";
    }

    private static string WriteNonNullConverter(LeafType leaf) => leaf.Kind switch
    {
        LeafTypeKind.Boolean => "e.GetBoolean()",
        LeafTypeKind.String => "e.GetString()!",
        LeafTypeKind.Guid => "e.GetGuid()",
        LeafTypeKind.DateTime => "e.GetDateTime()",
        LeafTypeKind.DateTimeOffset => "e.GetDateTimeOffset()",
        LeafTypeKind.Enum => $"global::System.Enum.Parse<{leaf.ClrTypeDisplay}>(e.GetString()!, ignoreCase: true)",
        LeafTypeKind.Integer or LeafTypeKind.Number => WriteNumericConverter(leaf.ClrTypeDisplay),
        _ => throw new InvalidOperationException($"Beklenmeyen yaprak tip: {leaf.Kind}"),
    };

    private static string WriteNumericConverter(string clrTypeDisplay) => clrTypeDisplay switch
    {
        "global::System.SByte" => "e.GetSByte()",
        "global::System.Byte" => "e.GetByte()",
        "global::System.Int16" => "e.GetInt16()",
        "global::System.UInt16" => "e.GetUInt16()",
        "global::System.Int32" => "e.GetInt32()",
        "global::System.UInt32" => "e.GetUInt32()",
        "global::System.Int64" => "e.GetInt64()",
        "global::System.UInt64" => "e.GetUInt64()",
        "global::System.Single" => "e.GetSingle()",
        "global::System.Double" => "e.GetDouble()",
        "global::System.Decimal" => "e.GetDecimal()",
        _ => throw new InvalidOperationException($"Beklenmeyen sayisal tip: {clrTypeDisplay}"),
    };

    private static string BuildSchema(EquatableArray<ParameterModel> parameters)
    {
        var properties = new StringBuilder();
        var required = new List<string>();
        var first = true;

        foreach (var parameter in parameters)
        {
            if (parameter.Shape == ParameterShape.CancellationToken)
            {
                continue;
            }

            if (!first)
            {
                properties.Append(',');
            }

            first = false;

            properties.Append('"').Append(JsonEscape(parameter.Name)).Append("\":").Append(BuildSchemaNode(parameter));

            if (parameter.IsRequired)
            {
                required.Add(parameter.Name);
            }
        }

        var requiredJson = string.Join(",", required.ConvertAll(name => $"\"{JsonEscape(name)}\""));

        return $"{{\"type\":\"object\",\"properties\":{{{properties}}},\"required\":[{requiredJson}],\"additionalProperties\":false}}";
    }

    private static string BuildSchemaNode(ParameterModel parameter)
    {
        var leafNode = BuildLeafSchemaNode(parameter.Leaf!);

        return parameter.Shape == ParameterShape.Array
            ? $"{{\"type\":\"array\",\"items\":{leafNode}}}"
            : leafNode;
    }

    private static string BuildLeafSchemaNode(LeafType leaf) => leaf.Kind switch
    {
        LeafTypeKind.Boolean => "{\"type\":\"boolean\"}",
        LeafTypeKind.Integer => "{\"type\":\"integer\"}",
        LeafTypeKind.Number => "{\"type\":\"number\"}",
        LeafTypeKind.String => "{\"type\":\"string\"}",
        LeafTypeKind.Guid => "{\"type\":\"string\",\"format\":\"uuid\"}",
        LeafTypeKind.DateTime or LeafTypeKind.DateTimeOffset => "{\"type\":\"string\",\"format\":\"date-time\"}",
        LeafTypeKind.Enum => "{\"type\":\"string\",\"enum\":[" + string.Join(",", leaf.EnumMemberNames.Select(n => $"\"{JsonEscape(n)}\"")) + "]}",
        _ => throw new InvalidOperationException($"Beklenmeyen yaprak tip: {leaf.Kind}"),
    };

    private static string JsonEscape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"");

    private static string ToStringLiteral(string value)
    {
        var sb = new StringBuilder(value.Length + 2).Append('"');

        foreach (var c in value)
        {
            sb.Append(c switch
            {
                '"' => "\\\"",
                '\\' => "\\\\",
                '\n' => "\\n",
                '\r' => "\\r",
                _ => c.ToString(),
            });
        }

        return sb.Append('"').ToString();
    }
}
