namespace Tracon.Generators.UnitTests;

/// <summary>
/// Verifies 52.5's three concrete guarantees: the <c>&lt;auto-generated/&gt;</c> header,
/// <c>dotnet format</c>-compatible formatting, and AOT-safe (reflection-free) code.
/// </summary>
public sealed class GeneratedCodeStructureTests
{
    private const string Source = """
        using Tracon;

        namespace MyApp;

        internal static class Tools
        {
            [TraconTool("get_order_status", "Returns the status of an order.")]
            public static string GetOrderStatus(string orderId) => orderId;
        }
        """;

    [Fact]
    public void Every_generated_file_carries_the_auto_generated_header()
    {
        var result = GeneratorTestHelper.Run(Source);

        result.GeneratedFiles().ShouldNotBeEmpty();

        foreach (var (hintName, text) in result.GeneratedFiles())
        {
            text.ShouldStartWith("// <auto-generated/>", customMessage: $"{hintName} has no header");
        }
    }

    [Fact]
    public void Generated_code_carries_no_tabs_or_trailing_whitespace()
    {
        // The two issues dotnet format catches most often: TAB characters and
        // trailing whitespace at end of line (IDE0055). A full `dotnet format
        // --verify-no-changes` run happens separately, on the sample app
        // (docs/arsiv/fazlar/52-KAYNAK-URETECI.md); here we isolate the generator's own output.
        var result = GeneratorTestHelper.Run(Source);

        foreach (var (hintName, text) in result.GeneratedFiles())
        {
            text.ShouldNotContain('\t', customMessage: $"{hintName} contains a TAB");

            foreach (var line in text.Split('\n'))
            {
                var trimmed = line.TrimEnd('\r');
                trimmed.ShouldBe(trimmed.TrimEnd(' '), customMessage: $"{hintName} has trailing whitespace: '{trimmed}'");
            }
        }
    }

    [Fact]
    public void Generated_code_uses_no_reflection_APIs()
    {
        // AOT definition of done: the generated path must NOT REQUIRE
        // [RequiresUnreferencedCode]/[RequiresDynamicCode]. The structural proof of
        // this is that the code never calls into reflection APIs at all - the real AOT
        // publish check (an IL2026/IL3050 scan) happens separately, on the sample app.
        var result = GeneratorTestHelper.Run(Source);

        string[] forbidden = ["System.Reflection", "Activator.", "GetMethod(", "GetMethods(", "MakeGenericType", "InvokeMember"];

        foreach (var (hintName, text) in result.GeneratedFiles())
        {
            foreach (var pattern in forbidden)
            {
                text.ShouldNotContain(pattern, customMessage: $"{hintName} carries a reflection trace: {pattern}");
            }
        }
    }

    [Fact]
    public void The_generated_class_derives_AIFunction_directly_and_does_not_use_AIFunctionFactory()
    {
        // Delegate-based AIFunctionFactory.Create also carries reflection (RequiresUnreferencedCode);
        // the generator's AOT promise is only kept by deriving AIFunction DIRECTLY.
        var result = GeneratorTestHelper.Run(Source);

        var wrapper = result.SingleWrapperFile();

        wrapper.ShouldContain(": global::Microsoft.Extensions.AI.AIFunction");
        wrapper.ShouldNotContain("AIFunctionFactory");
    }
}
