using System.Reflection;
using System.Text.Json;
using Tracon.Client.Generated;

namespace Tracon.Client.UnitTests;

/// <summary>
/// Proves that <see cref="TraconApiClient"/> has a public method for every
/// <c>operationId</c> in <c>docs/openapi/tracon.json</c> (section 83.2).
/// </summary>
/// <remarks>
/// The document is the production source; the generated client is a
/// downstream artifact regenerated by <c>dotnet nswag run nswag.json</c>. If
/// a phase adds an endpoint and regenerates the OpenAPI snapshot
/// (<c>OpenApiSnapshotTests</c>) without also re-running NSwag, this test
/// fails instead of the client silently going stale. There is no exemption
/// list: the document has zero operations without an <c>operationId</c>
/// today (measured 2026-08-21).
/// </remarks>
public sealed class ClientCoverageTests
{
    private static readonly string[] HttpMethods = ["get", "post", "put", "delete", "patch", "options", "head", "trace"];

    [Fact]
    public void Every_operationId_has_a_matching_client_method()
    {
        var operationIds = ReadOperationIds();

        var clientMethodNames = typeof(TraconApiClient)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Select(method => method.Name)
            .ToHashSet(StringComparer.Ordinal);

        var missing = operationIds
            .Where(operationId => !clientMethodNames.Contains($"{operationId}Async"))
            .Order(StringComparer.Ordinal)
            .ToList();

        missing.ShouldBeEmpty(
            customMessage: $"{missing.Count} operationId(s) have no matching '<operationId>Async' method on " +
                            "TraconApiClient. Regenerate the client: dotnet tool restore && " +
                            "python3 scripts/nswag-prepare-document.py docs/openapi/tracon.json " +
                            "artifacts/openapi/tracon.client-input.json && dotnet nswag run nswag.json && " +
                            "python3 scripts/nswag-postprocess-client.py src/Tracon.Client/Generated/TraconApiClient.g.cs " +
                            "docs/openapi/tracon.json && " +
                            "python3 scripts/generate-client-json-context.py src/Tracon.Client/Generated/TraconApiClient.g.cs " +
                            "src/Tracon.Client/Generated/TraconClientJsonContext.g.cs");
    }

    [Fact]
    public void Every_streaming_operation_has_a_matching_StreamAsync_method()
    {
        // The ratchet for nswag-postprocess-client.py's sixth pass (Phase 159).
        // A new text/event-stream endpoint is otherwise callable in exactly one
        // shape - the whole body buffered into a string, or, for a dual
        // JSON/SSE operation, not callable in its streaming shape at all - and
        // the test above would still pass, because the JSON method exists.
        var streamingOperationIds = ReadStreamingOperationIds();

        streamingOperationIds.ShouldNotBeEmpty();

        var clientMethodNames = typeof(TraconApiClient)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Select(method => method.Name)
            .ToHashSet(StringComparer.Ordinal);

        var missing = streamingOperationIds
            .Where(operationId => !clientMethodNames.Contains($"{operationId}StreamAsync"))
            .Order(StringComparer.Ordinal)
            .ToList();

        missing.ShouldBeEmpty(
            customMessage: $"{missing.Count} operation(s) declare a text/event-stream 200 response but have " +
                            "no '<operationId>StreamAsync' method. Regenerate the client with the document " +
                            "argument the sixth pass needs: python3 scripts/nswag-postprocess-client.py " +
                            "src/Tracon.Client/Generated/TraconApiClient.g.cs docs/openapi/tracon.json");
    }

    [Fact]
    public void Every_StreamAsync_method_streams_frames_rather_than_buffering_the_body()
    {
        // The shape is the contract: IAsyncEnumerable<string> is what makes a
        // frame reach the caller as the server flushes it, and what makes an
        // early break or a cancelled token stop the read. A Task<string>
        // sibling would satisfy the name check above while buffering the whole
        // run - which is exactly the limitation phase 159 removed.
        var wrongShape = typeof(TraconApiClient)
            .GetMethods(BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly)
            .Where(method => method.Name.EndsWith("StreamAsync", StringComparison.Ordinal))
            .Where(method => method.ReturnType != typeof(IAsyncEnumerable<string>))
            .Select(method => $"{method.Name} -> {method.ReturnType.Name}")
            .Order(StringComparer.Ordinal)
            .ToList();

        wrongShape.ShouldBeEmpty();
    }

    [Fact]
    public void The_document_has_no_operation_without_an_operationId()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(DocumentPath));

        var operationsWithoutId = document.RootElement.GetProperty("paths").EnumerateObject()
            .SelectMany(path => path.Value.EnumerateObject())
            .Where(method => HttpMethods.Contains(method.Name, StringComparer.Ordinal))
            .Where(method => !method.Value.TryGetProperty("operationId", out _))
            .Count();

        // 83.2's coverage gate has no exemption list; this documents WHY -
        // if this ever fails, ClientCoverageTests above needs one.
        operationsWithoutId.ShouldBe(0);
    }

    private static List<string> ReadStreamingOperationIds()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(DocumentPath));

        return document.RootElement.GetProperty("paths").EnumerateObject()
            .SelectMany(path => path.Value.EnumerateObject())
            .Where(method => HttpMethods.Contains(method.Name, StringComparer.Ordinal))
            .Where(method => method.Value.TryGetProperty("responses", out var responses)
                && responses.TryGetProperty("200", out var ok)
                && ok.TryGetProperty("content", out var content)
                && content.TryGetProperty("text/event-stream", out _))
            .Select(method => method.Value.GetProperty("operationId").GetString()!)
            .ToList();
    }

    private static List<string> ReadOperationIds()
    {
        using var document = JsonDocument.Parse(File.ReadAllText(DocumentPath));

        return document.RootElement.GetProperty("paths").EnumerateObject()
            .SelectMany(path => path.Value.EnumerateObject())
            .Where(method => HttpMethods.Contains(method.Name, StringComparer.Ordinal))
            .Select(method => method.Value.GetProperty("operationId").GetString()!)
            .ToList();
    }

    private static string RepositoryRoot { get; } = FindRepositoryRoot();

    private static string DocumentPath { get; } =
        Path.Combine(RepositoryRoot, "docs", "openapi", "tracon.json");

    private static string FindRepositoryRoot()
    {
        var directory = new DirectoryInfo(AppContext.BaseDirectory);

        while (directory is not null && !File.Exists(Path.Combine(directory.FullName, "Tracon.slnx")))
        {
            directory = directory.Parent;
        }

        return directory?.FullName ?? throw new InvalidOperationException("Tracon.slnx not found.");
    }
}
