using System.Text.Json;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;

namespace AgentPrism;

/// <summary>
/// Workflow catalog, definition management, execution, and checkpoint endpoints.
/// </summary>
/// <remarks>
/// <para>
/// The <see cref="IWorkflowRunner"/> and <c>IWorkflowCheckpointStore</c>
/// parameters are <strong>explicitly</strong> marked with <c>[FromServices]</c>.
/// Minimal API, seeing a type that may not be registered, falls back to body
/// inference, and this mistake on a single endpoint breaks <em>all</em>
/// endpoints - (112 of 119 tests failed at once, and the
/// error message was disconnected from the cause).
/// </para>
/// <para>
/// If the execution engine is not registered, the run endpoints return
/// <c>501</c>; definition management continues to work. The same pattern was
/// established for the MCP refresh endpoint.
/// </para>
/// </remarks>
internal static class WorkflowEndpoints
{
    private static JsonSerializerOptions JsonOptions { get; } = new(JsonSerializerDefaults.Web);

    /// <summary>Maps the workflow endpoints.</summary>
    /// <param name="builder">The endpoint group.</param>
    /// <param name="roles">The resolved role policies.</param>
    public static void Map(IEndpointRouteBuilder builder, AgentPrismRolePolicies roles)
    {
        builder.MapGet("/api/workflows", ListAsync)
            .RequireRole(roles.Reader)
            .RequireApiKeyScope(ApiKeyScope.WorkflowsRead)
            .WithName("AgentPrismListWorkflows")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Lists workflows defined in code and stored in the database.")
            .WithDescription(
                "What the list contains depends on whether the workflow engine is registered. " +
                "With the engine, both code-defined and stored workflows appear, because only " +
                "the engine can see the ones built in code. Without it, only stored definitions " +
                "are listed — managing definitions does not require the engine, but running them " +
                "does.");

        builder.MapGet("/api/workflows/functions", ListFunctionsAsync)
            .RequireRole(roles.Reader)
            .RequireApiKeyScope(ApiKeyScope.WorkflowsRead)
            .WithName("AgentPrismListWorkflowFunctions")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Lists function nodes registered in code.")
            .WithDescription(
                "Function nodes are defined only in code, with AddWorkflowFunction() - " +
                "the same code-only boundary AddTool draws for tools. This endpoint does not offer a write " +
                "path; the UI lets users pick from this list when building a Sequential workflow's " +
                "node list. An empty list means no function was registered, or the workflow engine " +
                "was never turned on with UseWorkflows() - either way, existing agent-only " +
                "workflows are unaffected.");

        builder.MapGet("/api/workflows/{name}", GetAsync)
            .RequireRole(roles.Reader)
            .RequireApiKeyScope(ApiKeyScope.WorkflowsRead)
            .WithName("AgentPrismGetWorkflow")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Returns a single workflow definition.")
            .WithDescription(
                "Only stored definitions are editable and only they are returned here. A " +
                "code-defined workflow is listed and can be run but has no stored definition, so " +
                "it answers 404 with a distinct 'No editable definition' title — different from " +
                "the plain not-found title used for a name that does not exist at all. Read the " +
                "structure of a code-defined workflow from the graph endpoint instead.");

        builder.MapGet("/api/workflows/{name}/graph", GetGraphAsync)
            .RequireRole(roles.Reader)
            .RequireApiKeyScope(ApiKeyScope.WorkflowsRead)
            .WithName("AgentPrismGetWorkflowGraph")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Returns the compiled graph of the workflow.")
            .WithDescription(
                "Node IDs are identical to the executor IDs in run events; this is how the UI " +
                "colors nodes live. The response also carries the Mermaid text generated by " +
                "Microsoft Agent Framework.");

        builder.MapPut("/api/workflows/{name}", SaveAsync)
            .RequireRole(roles.Admin)
            .RequireApiKeyScope(ApiKeyScope.WorkflowsAdmin)
            .WithName("AgentPrismSaveWorkflow")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Creates or updates a workflow definition.")
            .WithDescription(
                "The definition is validated at save time with the same rules the compiler " +
                "applies, so a shape that could not run is rejected with 400 instead of failing " +
                "on the first run. Which fields are required depends on the kind — a manager " +
                "driven workflow needs its manager agent, for example. The call replaces the " +
                "whole definition: omitted fields are cleared, not merged. The name comes from " +
                "the path and is not taken from the body.")
            .Accepts<WorkflowSaveRequest>("application/json");

        builder.MapDelete("/api/workflows/{name}", DeleteAsync)
            .RequireRole(roles.Admin)
            .RequireApiKeyScope(ApiKeyScope.WorkflowsAdmin)
            .WithName("AgentPrismDeleteWorkflow")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Deletes a workflow definition.")
            .WithDescription(
                "Only a stored definition can be deleted; a code-defined workflow is removed by " +
                "changing the application, and asking for one here returns 404. Runs and " +
                "checkpoints already recorded are kept, so past executions stay readable, but a " +
                "checkpoint cannot be resumed once the definition it needs is gone.");

        builder.MapPost("/api/workflows/{name}/run", RunAsync)
            .RequireRole(roles.Operator)
            .RequireApiKeyScope(ApiKeyScope.RunsWrite)
            .WithName("AgentPrismRunWorkflow")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Runs the workflow and streams its events over SSE.")
            .Accepts<WorkflowRunHttpRequest>(true, "application/json")
            .WithDescription(
                "Each frame carries a RunEvent. The first frame reports the run ID; every " +
                "agent invoked within the workflow opens its own runs row, viewable as a tree " +
                "via GET /api/runs/{runId}/tree.")
            // The success response is always SSE; if the engine is not registered, it returns 501.
            .Produces<string>(StatusCodes.Status200OK, contentType: "text/event-stream")
            .ProducesProblem(StatusCodes.Status404NotFound)
            .ProducesProblem(StatusCodes.Status429TooManyRequests)
            .ProducesProblem(StatusCodes.Status501NotImplemented);

        builder.MapGet("/api/workflows/runs/{runId:guid}/checkpoints", ListCheckpointsAsync)
            .RequireRole(roles.Reader)
            .RequireApiKeyScope(ApiKeyScope.RunsRead)
            .WithName("AgentPrismListWorkflowCheckpoints")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Lists the checkpoints of a workflow run.")
            .WithDescription(
                "Checkpoints are the points a run can be resumed from; each entry's id is what " +
                "the resume endpoint takes. A run belonging to another tenant is reported as " +
                "404 rather than 403, so the API does not confirm that it exists. An empty list " +
                "means the run wrote no checkpoint — checkpointing is a property of how the " +
                "workflow was built, not something this endpoint can turn on. Checkpoints are " +
                "subject to retention, so an old run may have none left.");

        builder.MapPost("/api/workflows/runs/{runId:guid}/resume", ResumeAsync)
            .RequireRole(roles.Operator)
            .RequireApiKeyScope(ApiKeyScope.RunsWrite)
            .WithName("AgentPrismResumeWorkflow")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Resumes from a checkpoint and streams events over SSE.")
            .WithDescription(
                "Resuming opens a NEW run rather than continuing the old one: the original run " +
                "row is never rewritten, and the first streamed frame reports the new run id. " +
                "The body is optional — without a checkpoint id the run resumes from its latest " +
                "checkpoint. The engine must be registered; otherwise the response is 501. " +
                "Because the status code is sent before the stream begins, a failure after that " +
                "point arrives as an SSE error frame rather than an HTTP error.")
            .Accepts<WorkflowResumeHttpRequest>(true, "application/json")
            .Produces<string>(StatusCodes.Status200OK, contentType: "text/event-stream")
            .ProducesProblem(StatusCodes.Status501NotImplemented);

        builder.MapGet("/api/workflows/runs/{runId:guid}/requests", ListRequestsAsync)
            .RequireRole(roles.Reader)
            .RequireApiKeyScope(ApiKeyScope.RunsRead)
            .WithName("AgentPrismListWorkflowRequests")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Lists a run's pending human input requests.")
            .WithDescription(
                "Only a run in the 'AwaitingInput' state returns requests. Requests are read " +
                "from the run's event stream; there is no separate table.");

        builder.MapPost("/api/workflows/runs/{runId:guid}/respond", RespondAsync)
            .RequireRole(roles.Operator)
            .RequireApiKeyScope(ApiKeyScope.RunsWrite)
            .WithName("AgentPrismRespondWorkflowRequest")
            .WithTags("AgentPrism", "Workflows")
            .WithSummary("Responds to a pending request and resumes the run.")
            .Accepts<WorkflowRespondHttpRequest>(true, "application/json")
            .WithDescription(
                "The response is matched to the request re-published with the same ID in the " +
                "execution resumed from the checkpoint. Resuming opens a NEW runs row; events " +
                "stream over SSE.")
            .Produces<string>(StatusCodes.Status200OK, contentType: "text/event-stream")
            .ProducesProblem(StatusCodes.Status400BadRequest)
            .ProducesProblem(StatusCodes.Status501NotImplemented);
    }

    private static async Task<Results<Ok<IReadOnlyList<WorkflowDescriptor>>, ProblemHttpResult>> ListAsync(
        [FromServices] IWorkflowDefinitionStore store,
        [FromServices] ITenantContext tenants,
        [FromServices] IWorkflowRunner? runner,
        CancellationToken cancellationToken)
    {
        // If the engine is registered, the catalog is read from it: only it
        // can also see workflows defined in code. If not registered,
        // database definitions are still listed - definition management is
        // independent of the engine.
        if (runner is not null)
        {
            return TypedResults.Ok(await runner.ListAsync(cancellationToken).ConfigureAwait(false));
        }

        var stored = await store.ListAsync(tenants.TenantId, cancellationToken).ConfigureAwait(false);

        return TypedResults.Ok<IReadOnlyList<WorkflowDescriptor>>(
            [.. stored.Select(Describe)]);
    }

    private static Ok<IReadOnlyList<WorkflowFunctionResponse>> ListFunctionsAsync(
        [FromServices] IWorkflowFunctionCatalog? functions)
        // No function is ever registered, or UseWorkflows() was never called:
        // an empty list, not a 501 - listing functions does not need the
        // execution engine, the same reasoning ListAsync applies to workflows.
        => TypedResults.Ok<IReadOnlyList<WorkflowFunctionResponse>>(
            [.. (functions?.List() ?? []).Select(WorkflowFunctionResponse.From)]);

    private static async Task<Results<Ok<WorkflowDefinition>, ProblemHttpResult>> GetAsync(
        string name,
        [FromServices] IWorkflowDefinitionStore store,
        [FromServices] ITenantContext tenants,
        [FromServices] IWorkflowRunner? runner,
        CancellationToken cancellationToken)
    {
        var definition = await store.GetAsync(tenants.TenantId, name, cancellationToken).ConfigureAwait(false);

        if (definition is not null)
        {
            return TypedResults.Ok(definition);
        }

        // 🚨 A CODE-defined workflow (AddWorkflow(...)) is never written to
        // IWorkflowDefinitionStore — it is a free-standing Workflow graph and
        // NEVER has an editable WorkflowDefinition (see
        // CodeWorkflowRegistration). It is confusing for this endpoint to say
        // "not found" while the workflow appears in the list and can be run;
        // at least the REASON is distinguished.
        if (runner is not null && await runner.GetAsync(name, cancellationToken).ConfigureAwait(false) is not null)
        {
            return TypedResults.Problem(
                title: "No editable definition",
                detail: $"'{name}' is a workflow defined in code (AddWorkflow). It is listed and " +
                        "can be run, but does not carry an editable WorkflowDefinition in the database.",
                statusCode: StatusCodes.Status404NotFound);
        }

        return NotFound(name);
    }

    private static async Task<Results<Ok<WorkflowGraph>, ProblemHttpResult>> GetGraphAsync(
        string name,
        [FromServices] IWorkflowRunner? runner,
        CancellationToken cancellationToken)
    {
        // The graph is extracted from the COMPILED workflow; a graph drawn
        // from the definition would not show nodes added by built-in
        // patterns, and run events would not match any node. Requires the
        // execution engine.
        if (runner is null)
        {
            return NotRegistered();
        }

        WorkflowGraph? graph;

        try
        {
            graph = await runner.GetGraphAsync(name, cancellationToken).ConfigureAwait(false);
        }
        catch (AgentPrismException exception)
        {
            // An invalid definition or an agent missing from the catalog:
            // this is an error the user can fix, not a server error.
            return TypedResults.Problem(
                title: "Workflow graph could not be extracted",
                detail: exception.Message,
                statusCode: StatusCodes.Status400BadRequest);
        }

        return graph is null ? NotFound(name) : TypedResults.Ok(graph);
    }

    private static async Task<Results<Ok<WorkflowDefinition>, ProblemHttpResult>> SaveAsync(
        string name,
        HttpContext httpContext,
        [FromServices] IWorkflowDefinitionStore store,
        [FromServices] ITenantContext tenants,
        [FromServices] IWorkflowFunctionCatalog? functions,
        CancellationToken cancellationToken)
    {
        var (bound, bindError) = await RequestBodyBinding
            .ReadAsync<WorkflowSaveRequest>(httpContext, cancellationToken)
            .ConfigureAwait(false);

        if (bindError is not null)
        {
            return bindError;
        }

        var request = bound!;

        var definition = new WorkflowDefinition
        {
            Name = name,
            DisplayName = request.DisplayName,
            Description = request.Description,
            Kind = request.Kind,
            AgentNames = request.AgentNames ?? [],
            Nodes = request.Nodes ?? [],
            ManagerAgentName = request.ManagerAgentName,
            MaxIterations = request.MaxIterations,
            HandoffInstructions = request.HandoffInstructions,
            RequirePlanApproval = request.RequirePlanApproval,
        };

        // Validation happens AT SAVE TIME. Accepting an invalid definition
        // and blowing up at run time would force the user to start a run
        // just to find the error. The workflow compiler uses the same
        // check; the rule lives in a single place (AgentPrism.Core).
        if (WorkflowDefinitionValidator.Validate(definition) is { } message)
        {
            return TypedResults.Problem(
                title: "Workflow definition invalid",
                detail: message,
                statusCode: StatusCodes.Status400BadRequest);
        }

        // A function node's name IS checked at save time, unlike an agent
        // name (agents live in a store that can change after save; the
        // function registry is fixed in code for the process lifetime, so
        // checking early gives an honest guarantee - phase 71).
        foreach (var node in definition.Nodes)
        {
            if (node.Kind != WorkflowNodeKind.Function)
            {
                continue;
            }

            if (functions is null || !functions.Contains(node.Name))
            {
                return TypedResults.Problem(
                    title: "Workflow definition invalid",
                    detail: $"Workflow '{name}' uses function '{node.Name}', but no such function is " +
                            "registered. Register it with AddWorkflowFunction() before referencing it " +
                            "from a workflow definition.",
                    statusCode: StatusCodes.Status400BadRequest);
            }
        }

        var saved = await store.SaveAsync(tenants.TenantId, definition, cancellationToken).ConfigureAwait(false);

        return TypedResults.Ok(saved);
    }

    private static async Task<Results<NoContent, ProblemHttpResult>> DeleteAsync(
        string name,
        [FromServices] IWorkflowDefinitionStore store,
        [FromServices] ITenantContext tenants,
        CancellationToken cancellationToken)
        => await store.DeleteAsync(tenants.TenantId, name, cancellationToken).ConfigureAwait(false)
            ? TypedResults.NoContent()
            : NotFound(name);

    private static async Task<IResult> RunAsync(
        string name,
        [FromServices] IWorkflowRunner? runner,
        [FromServices] QuotaEnforcer? quotaEnforcer,
        [FromServices] ITenantContext tenantContext,
        HttpContext httpContext,
        CancellationToken cancellationToken)
    {
        if (runner is null)
        {
            return NotRegistered();
        }

        var (request, bindError) = await RequestBodyBinding
            .ReadOptionalAsync<WorkflowRunHttpRequest>(httpContext, cancellationToken)
            .ConfigureAwait(false);

        if (bindError is not null)
        {
            return bindError;
        }

        if (await runner.GetAsync(name, cancellationToken).ConfigureAwait(false) is null)
        {
            return NotFound(name);
        }

        // 🚨 HATA-S1-006: workflow runs pass through the SAME quota gate as
        // agents (see AgentEndpoints.cs, same pattern) — this check did not
        // exist before, and any defined quota (run count, tokens, cost)
        // could be bypassed via workflows.
        if (await QuotaGate
                .CheckAsync(quotaEnforcer, tenantContext, name, httpContext, cancellationToken)
                .ConfigureAwait(false) is { } quotaProblem)
        {
            return quotaProblem;
        }

        var runId = AgentPrismId.NewId();

        return new WorkflowEventStream(
            runner.RunStreamingAsync(
                new WorkflowRunRequest
                {
                    WorkflowName = name,
                    Message = request?.Message,
                    SessionId = request?.SessionId,
                    RunId = runId,
                },
                cancellationToken),
            runId);
    }

    private static async Task<Results<Ok<IReadOnlyList<WorkflowCheckpointRecord>>, ProblemHttpResult>>
        ListCheckpointsAsync(
            Guid runId,
            [FromServices] IWorkflowCheckpointStore checkpoints,
            [FromServices] IRunStore runs,
            [FromServices] ITenantContext tenants,
            CancellationToken cancellationToken)
    {
        var record = await runs.GetRunAsync(runId, cancellationToken).ConfigureAwait(false);

        // If the tenant does not match, "not found" is returned; the
        // existence of another tenant's run is not leaked.
        if (record is null || !string.Equals(record.TenantId, tenants.TenantId, StringComparison.Ordinal))
        {
            return RunNotFound(runId);
        }

        var list = await checkpoints
            .ListByRunAsync(tenants.TenantId, runId, cancellationToken)
            .ConfigureAwait(false);

        return TypedResults.Ok(list);
    }

    private static async Task<IResult> ResumeAsync(
        Guid runId,
        HttpContext httpContext,
        [FromServices] IWorkflowRunner? runner,
        CancellationToken cancellationToken)
    {
        if (runner is null)
        {
            return NotRegistered();
        }

        var (request, bindError) = await RequestBodyBinding
            .ReadOptionalAsync<WorkflowResumeHttpRequest>(httpContext, cancellationToken)
            .ConfigureAwait(false);

        if (bindError is not null)
        {
            return bindError;
        }

        var newRunId = AgentPrismId.NewId();

        return new WorkflowEventStream(
            runner.ResumeStreamingAsync(
                new WorkflowResumeRequest
                {
                    RunId = runId,
                    CheckpointId = request?.CheckpointId,
                    NewRunId = newRunId,
                },
                cancellationToken),
            newRunId);
    }

    private static async Task<Results<Ok<IReadOnlyList<WorkflowPendingRequest>>, ProblemHttpResult>>
        ListRequestsAsync(
            Guid runId,
            [FromServices] IWorkflowRunner? runner,
            CancellationToken cancellationToken)
    {
        if (runner is null)
        {
            return NotRegistered();
        }

        try
        {
            var requests = await runner.ListPendingRequestsAsync(runId, cancellationToken).ConfigureAwait(false);

            return TypedResults.Ok(requests);
        }
        catch (AgentPrismException exception)
        {
            // A tenant mismatch also falls into this catch and is answered
            // as "not found"; the existence of another tenant's run is not
            // leaked.
            return TypedResults.Problem(
                title: "Run not found",
                detail: exception.Message,
                statusCode: StatusCodes.Status404NotFound);
        }
    }

    private static async Task<IResult> RespondAsync(
        Guid runId,
        HttpContext httpContext,
        [FromServices] IWorkflowRunner? runner,
        CancellationToken cancellationToken)
    {
        if (runner is null)
        {
            return NotRegistered();
        }

        var (request, bindError) = await RequestBodyBinding
            .ReadOptionalAsync<WorkflowRespondHttpRequest>(httpContext, cancellationToken)
            .ConfigureAwait(false);

        if (bindError is not null)
        {
            return bindError;
        }

        if (request is null || string.IsNullOrWhiteSpace(request.RequestId))
        {
            return TypedResults.Problem(
                title: "Response invalid",
                detail: "'requestId' is required.",
                statusCode: StatusCodes.Status400BadRequest);
        }

        var newRunId = AgentPrismId.NewId();

        return new WorkflowEventStream(
            runner.RespondStreamingAsync(
                new WorkflowRespondRequest
                {
                    RunId = runId,
                    RequestId = request.RequestId,
                    Approved = request.Approved,
                    Text = request.Text,

                    // The raw JSON text is carried: the response type can
                    // only be resolved at run time, according to the type
                    // reported by the port.
                    Json = request.Data?.GetRawText(),
                    CheckpointId = request.CheckpointId,
                    NewRunId = newRunId,
                },
                cancellationToken),
            newRunId);
    }

    private static WorkflowDescriptor Describe(WorkflowDefinition definition)
        => new()
        {
            Name = definition.Name,
            DisplayName = definition.DisplayName,
            Description = definition.Description,
            Origin = AgentDefinitionOrigin.Database,
            Kind = definition.Kind,
            AgentNames = definition.AgentNames,
            Nodes = definition.Nodes,
            Version = definition.Version,
            UpdatedAt = definition.UpdatedAt,
        };

    private static ProblemHttpResult NotRegistered()
        => TypedResults.Problem(
            title: "Workflow engine not registered",
            detail: "Add the AgentPrism.Workflows package and call UseWorkflows() to run workflows.",
            statusCode: StatusCodes.Status501NotImplemented);

    private static ProblemHttpResult NotFound(string name)
        => TypedResults.Problem(
            title: "Workflow not found",
            detail: $"There is no workflow named '{name}'.",
            statusCode: StatusCodes.Status404NotFound);

    private static ProblemHttpResult RunNotFound(Guid runId)
        => TypedResults.Problem(
            title: "Run not found",
            detail: $"There is no run with id '{runId}'.",
            statusCode: StatusCodes.Status404NotFound);

    /// <summary>
    /// Writes workflow events as SSE.
    /// </summary>
    /// <remarks>
    /// Written as a separate <see cref="IResult"/> because the status code
    /// cannot be changed after the stream has started; an <c>event: error</c>
    /// frame is sent on failure. The same pattern is also used for agent trial runs.
    /// </remarks>
    private sealed class WorkflowEventStream(IAsyncEnumerable<RunEvent> events, Guid runId) : IResult
    {
        public async Task ExecuteAsync(HttpContext httpContext)
        {
            ArgumentNullException.ThrowIfNull(httpContext);

            var cancellationToken = httpContext.RequestAborted;
            var writer = await SseWriter.StartAsync(httpContext.Response, cancellationToken).ConfigureAwait(false);
            long sequence = 0;

            try
            {
                await writer.WriteEventAsync(
                    sequence++,
                    "run",
                    JsonSerializer.Serialize(new WorkflowRunAccepted(runId), JsonOptions),
                    cancellationToken).ConfigureAwait(false);

                await foreach (var runEvent in events.WithCancellation(cancellationToken).ConfigureAwait(false))
                {
                    await writer.WriteEventAsync(
                        sequence++,
                        "event",
                        JsonSerializer.Serialize(runEvent, JsonOptions),
                        cancellationToken).ConfigureAwait(false);
                }

                await writer.WriteEventAsync(
                    sequence,
                    "done",
                    JsonSerializer.Serialize(new WorkflowRunCompleted(runId), JsonOptions),
                    cancellationToken).ConfigureAwait(false);
            }
            catch (OperationCanceledException)
            {
                // The client disconnected. There is no one left to write to.
            }
            catch (Exception ex) when (ex is AgentPrismException or InvalidOperationException or HttpRequestException)
            {
                await writer.WriteEventAsync(
                    sequence,
                    "error",
                    JsonSerializer.Serialize(new WorkflowRunFailed(ex.GetType().Name, ex.Message), JsonOptions),
                    CancellationToken.None).ConfigureAwait(false);
            }
        }

        private sealed record WorkflowRunAccepted(Guid RunId);

        private sealed record WorkflowRunCompleted(Guid RunId);

        private sealed record WorkflowRunFailed(string Type, string Message);
    }
}
