<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../AgentPrism.Samples.CustomModelProvider/AgentPrism.Samples.CustomModelProvider.csproj" />
    <ProjectReference Include="../AgentPrism.Samples.CustomAgentSource/AgentPrism.Samples.CustomAgentSource.csproj" />
    <ProjectReference Include="../AgentPrism.Samples.CustomTool/AgentPrism.Samples.CustomTool.csproj" />
    <PackageReference Include="AgentPrism" VersionOverride="$(AgentPrismSamplePackageVersion)" />
  </ItemGroup>

</Project>
